import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
import joblib

print("Training Expanded AI Tutor Model (~3000 questions)...\n")

# ==============================================================================
# PHYSICS - 600 questions
# ==============================================================================
physics = [
    # --- Newton & Gravity (40) ---
    "How did Newton discover gravity?",
    "What inspired Newton to think about gravity?",
    "Tell me the story of Newton and the apple",
    "How was gravity discovered?",
    "Who discovered the law of gravitation?",
    "What is Newton's law of universal gravitation?",
    "How did scientists figure out gravity exists?",
    "What is the formula for gravitational force?",
    "Why do objects fall to the ground?",
    "What makes things fall down?",
    "How does gravity pull objects?",
    "What is the gravitational constant G?",
    "How does gravity work on Earth?",
    "What is the acceleration due to gravity?",
    "What is the formula for acceleration due to gravity?",
    "Why is gravity weaker on the moon?",
    "How did Galileo study gravity?",
    "What is gravitational potential energy?",
    "How does gravity affect satellites?",
    "What is free fall?",
    "Why do all objects fall at the same rate?",
    "What is the difference between weight and mass?",
    "How does gravity cause tides?",
    "What is weightlessness?",
    "Why do astronauts float in space?",
    "What is the value of g on Earth?",
    "How does altitude affect gravity?",
    "What is gravitational field?",
    "What is orbital mechanics?",
    "How does gravity keep the moon in orbit?",
    "Why is gravity a fundamental force?",
    "What is the difference between gravity and gravitational force?",
    "How did Einstein change our understanding of gravity?",
    "What is general relativity?",
    "What is space-time curvature?",
    "How does a black hole's gravity work?",
    "What is tidal force?",
    "What is the Cavendish experiment?",
    "How do we measure gravity?",
    "What is anti-gravity?",

    # --- Newton's Laws (30) ---
    "Explain Newton's three laws of motion",
    "What is Newton's first law?",
    "What is Newton's second law of motion?",
    "What is Newton's third law?",
    "Give an example of Newton's first law",
    "Give an example of Newton's third law in real life",
    "How do I calculate force using F equals ma?",
    "What is inertia?",
    "Why does a book stay on the table?",
    "Why does a rocket move forward?",
    "What is action and reaction?",
    "How does Newton's second law relate force and acceleration?",
    "What is the unit of force?",
    "Why does a passenger lurch forward when a bus brakes?",
    "How does Newton's first law apply to seat belts?",
    "What happens when two equal forces act in opposite directions?",
    "What is net force?",
    "How do Newton's laws apply to swimming?",
    "What is the law of inertia?",
    "How does friction relate to Newton's laws?",
    "What is balanced force?",
    "What is unbalanced force?",
    "How do Newton's laws explain car crashes?",
    "Why is it harder to push a heavier object?",
    "How does mass affect acceleration?",
    "What happens when no force acts on an object?",
    "How do Newton's laws apply to rockets?",
    "What is equilibrium in physics?",
    "Why does a gun recoil when fired?",
    "How does Newton's third law apply to walking?",

    # --- Energy & Work (30) ---
    "What is kinetic energy? Give formula",
    "What is potential energy?",
    "Explain the concept of work and energy",
    "State the law of conservation of energy",
    "What is the difference between kinetic and potential energy?",
    "How is work calculated in physics?",
    "What is mechanical energy?",
    "What is the unit of energy?",
    "What is power in physics?",
    "What is the unit of power?",
    "How is power related to work?",
    "What is energy transformation?",
    "Give examples of energy conversion",
    "What is elastic potential energy?",
    "What is chemical energy?",
    "What is nuclear energy?",
    "What is thermal energy?",
    "What is the work-energy theorem?",
    "What is efficiency in physics?",
    "How do you calculate efficiency?",
    "What is wasted energy?",
    "What is useful energy?",
    "Can energy be destroyed?",
    "What is the joule?",
    "What is a watt?",
    "How does a pendulum show energy conservation?",
    "What is internal energy?",
    "What is total mechanical energy?",
    "How is energy stored in a spring?",
    "What is work done against gravity?",

    # --- Motion & Kinematics (40) ---
    "What is acceleration? Unit of acceleration",
    "Difference between speed and velocity",
    "Explain projectile motion",
    "What is uniform motion?",
    "What is non-uniform motion?",
    "What are the equations of motion?",
    "What is displacement?",
    "What is distance vs displacement?",
    "How do you calculate velocity?",
    "What is average speed?",
    "What is instantaneous velocity?",
    "Explain uniform circular motion",
    "What is centripetal force?",
    "What is centrifugal force?",
    "What is angular velocity?",
    "What is torque?",
    "What is terminal velocity?",
    "What is escape velocity?",
    "What is relative velocity?",
    "What is frame of reference?",
    "What is a velocity-time graph?",
    "What is a distance-time graph?",
    "What is deceleration?",
    "What is circular motion?",
    "What is the first equation of motion?",
    "What is the second equation of motion?",
    "What is the third equation of motion v squared?",
    "How do you find initial velocity?",
    "What is range of a projectile?",
    "What is maximum height of a projectile?",
    "What angle gives maximum range in projectile?",
    "What is horizontal component of velocity?",
    "What is vertical component of velocity?",
    "How does gravity affect projectile motion?",
    "What is time of flight in projectile motion?",
    "What is curvilinear motion?",
    "What is angular acceleration?",
    "What is angular displacement?",
    "What is the relationship between linear and angular velocity?",
    "What is centripetal acceleration?",

    # --- Momentum (20) ---
    "What is momentum? Formula",
    "Law of conservation of momentum",
    "What is impulse?",
    "How is momentum related to force?",
    "What is collision in physics?",
    "Elastic vs inelastic collision",
    "What is perfectly inelastic collision?",
    "What is coefficient of restitution?",
    "How does airbag use impulse?",
    "Why does a cricket ball hurt more than a tennis ball?",
    "What happens to momentum in explosions?",
    "What is angular momentum?",
    "What is conservation of angular momentum?",
    "Why does a spinning top not fall?",
    "Why do ice skaters spin faster when they pull in arms?",
    "What is the unit of momentum?",
    "How does momentum relate to Newton's second law?",
    "What is center of mass?",
    "How is momentum conserved in billiards?",
    "What is recoil velocity?",

    # --- Forces & Friction (20) ---
    "What is friction? Types of friction",
    "What is static friction?",
    "What is kinetic friction?",
    "How does friction affect motion?",
    "What is normal force?",
    "What is tension in physics?",
    "What is coefficient of friction?",
    "How do you calculate frictional force?",
    "What is rolling friction?",
    "What is fluid friction?",
    "Why is friction necessary?",
    "How do brakes use friction?",
    "What is drag force?",
    "What is air resistance?",
    "What is the four fundamental forces?",
    "What is strong nuclear force?",
    "What is weak nuclear force?",
    "What is electromagnetic force?",
    "How does friction produce heat?",
    "What is lubrication?",

    # --- Waves & Sound (30) ---
    "Explain wave motion and types of waves",
    "Formula for wavelength frequency and speed",
    "What is resonance?",
    "Explain standing waves",
    "What is sound wave? Speed of sound",
    "What is echo?",
    "Explain SONAR",
    "Explain Doppler effect",
    "What is ultrasound?",
    "What is infrasound?",
    "What is amplitude of a wave?",
    "What is frequency?",
    "What is wavelength?",
    "What is the relationship between frequency and pitch?",
    "What is transverse wave?",
    "What is longitudinal wave?",
    "What is mechanical wave?",
    "What is electromagnetic wave?",
    "What is the speed of sound in air?",
    "Why does sound travel faster in solids?",
    "What is interference of waves?",
    "What is constructive interference?",
    "What is destructive interference?",
    "What is diffraction?",
    "What is polarization of light?",
    "What is the decibel scale?",
    "What is noise pollution?",
    "How does SONAR detect objects?",
    "What is pitch of sound?",
    "What is loudness?",

    # --- Light & Optics (30) ---
    "Explain reflection and refraction of light",
    "What is the lens formula?",
    "What is mirror formula?",
    "Difference between concave and convex lens",
    "Explain total internal reflection",
    "What is critical angle?",
    "What is optical fibre?",
    "What is the speed of light in vacuum?",
    "What is dispersion of light?",
    "What is rainbow?",
    "What is refractive index?",
    "What is prism?",
    "What is lens maker's formula?",
    "Explain LASER",
    "What is concave mirror?",
    "What is convex mirror?",
    "What is plane mirror?",
    "What is the law of reflection?",
    "What is Snell's law?",
    "What is the human eye?",
    "What is near sightedness?",
    "What is far sightedness?",
    "What is power of a lens?",
    "What is magnification?",
    "What is a microscope?",
    "What is a telescope?",
    "What is coherent light?",
    "What is monochromatic light?",
    "What is scattering of light?",
    "Why is the sky blue?",

    # --- Electricity & Magnetism (30) ---
    "What is Ohm's law?",
    "What is electric field?",
    "What is magnetic field?",
    "What is electromagnetic induction?",
    "Explain Faraday's law of induction",
    "Right hand thumb rule",
    "What is electric current?",
    "What is voltage?",
    "What is resistance?",
    "What is capacitor?",
    "What is inductor?",
    "Coulomb's law",
    "SI unit of electric current",
    "Difference between AC and DC current",
    "What is transformer?",
    "What is LED?",
    "What is transistor?",
    "Explain semiconductor",
    "What is diode?",
    "What is electric power?",
    "What is electric circuit?",
    "What is series circuit?",
    "What is parallel circuit?",
    "What is Kirchhoff's voltage law?",
    "What is Kirchhoff's current law?",
    "What is Fleming's left hand rule?",
    "What is an electric motor?",
    "What is an electric generator?",
    "What is magnetic flux?",
    "What is Lenz's law?",

    # --- Thermodynamics (25) ---
    "What is specific heat capacity?",
    "Explain latent heat of fusion and vaporization",
    "What is thermodynamics?",
    "Zeroth law of thermodynamics",
    "What is entropy?",
    "What is temperature?",
    "What is heat transfer?",
    "Explain conduction convection and radiation",
    "What is thermal expansion?",
    "What is first law of thermodynamics?",
    "What is second law of thermodynamics?",
    "What is third law of thermodynamics?",
    "What is heat engine?",
    "What is Carnot engine?",
    "What is efficiency of heat engine?",
    "What is refrigerator in thermodynamics?",
    "What is absolute zero?",
    "What is Kelvin scale?",
    "What is Celsius to Kelvin conversion?",
    "What is thermal equilibrium?",
    "What is heat capacity?",
    "What is calorimeter?",
    "What is Stefan-Boltzmann law?",
    "What is black body radiation?",
    "What is greenhouse effect?",

    # --- Fluid Mechanics (20) ---
    "Explain Archimedes principle",
    "What is Pascal's law?",
    "What is the formula for pressure?",
    "Principle of buoyancy",
    "What is viscosity?",
    "Explain surface tension",
    "Explain fluid dynamics",
    "Bernoulli's principle",
    "Why does a ship float?",
    "Why does ice float on water?",
    "What is laminar flow?",
    "What is turbulent flow?",
    "What is atmospheric pressure?",
    "What is gauge pressure?",
    "What is absolute pressure?",
    "How does a hydraulic press work?",
    "What is capillary action?",
    "What is Stokes law?",
    "What is Reynolds number?",
    "What is equation of continuity?",

    # --- Modern & Nuclear Physics (25) ---
    "Explain nuclear fission and nuclear fusion",
    "What is radioactivity?",
    "What is half-life of a radioactive substance?",
    "Explain photoelectric effect",
    "What is Planck's constant?",
    "Basics of quantum mechanics",
    "Theory of relativity by Einstein",
    "What is alpha beta and gamma decay?",
    "What is binding energy?",
    "Explain mass defect",
    "What is nuclear reactor?",
    "What is X-ray?",
    "What is gamma ray?",
    "What is electromagnetic spectrum?",
    "What is matter wave?",
    "What is de Broglie wavelength?",
    "What is Heisenberg uncertainty principle?",
    "What is wave-particle duality?",
    "What is quantum tunneling?",
    "What is Schrodinger equation?",
    "What is nuclear force?",
    "What is mass-energy equivalence?",
    "What is E equals mc squared?",
    "What is antimatter?",
    "What is Compton effect?",

    # --- Celestial & Planetary (20) ---
    "Kepler's laws of planetary motion",
    "How did Kepler discover planetary motion?",
    "What is the story behind Kepler's laws?",
    "How do planets orbit the sun?",
    "What keeps planets in orbit?",
    "What is orbital velocity?",
    "What is black hole?",
    "What is the Big Bang theory?",
    "How was the universe formed?",
    "What is a star?",
    "What is a galaxy?",
    "What is the solar system?",
    "What is a comet?",
    "What is an asteroid?",
    "What is a supernova?",
    "What is neutron star?",
    "What is red giant?",
    "What is dark matter?",
    "What is dark energy?",
    "What is cosmic microwave background?",

    # --- Elasticity, Machines & Misc (30) ---
    "What is Hooke's law?",
    "Explain Young's modulus",
    "What is stress and strain?",
    "What is elastic limit?",
    "What is simple harmonic motion?",
    "What is a lever?",
    "What is a pulley?",
    "How does an inclined plane work?",
    "Difference between scalar and vector quantities",
    "What is dot product?",
    "What is cross product?",
    "How do you add vectors?",
    "What is a unit vector?",
    "What is resolution of vectors?",
    "What is resultant vector?",
    "What is moment of inertia?",
    "What is couple in physics?",
    "What is center of gravity?",
    "What is equilibrium of forces?",
    "What is the principle of moments?",
    "What is renewable vs non-renewable energy?",
    "What is solar cell?",
    "Explain wind energy",
    "What is hydropower?",
    "What is nuclear energy used for?",
    "What is ozone layer depletion?",
    "What is acid rain?",
    "What is global warming?",
    "What is climate change?",
    "What is the greenhouse effect?",
]

# ==============================================================================
# MATH - 600 questions
# ==============================================================================
math = [
    # --- Algebra (80) ---
    "Solve for x in 2x plus 5 equals 15",
    "Solve the quadratic equation x squared minus 5x plus 6 equals 0",
    "Solve 3x minus 7 equals 20",
    "Find the roots of x squared plus 4x plus 4 equals 0",
    "Solve 5x plus 3 equals 2x plus 15",
    "Solve x squared minus 9 equals 0",
    "Solve inequality 2x plus 5 greater than 17",
    "How do I solve linear equations?",
    "How do I expand brackets in algebra?",
    "Simplify x squared plus 5x plus 6 divided by x plus 2",
    "Solve the system of equations x plus y equals 10 and 2x minus y equals 4",
    "What is algebra?",
    "What is a variable in math?",
    "What is a coefficient?",
    "What is a constant in algebra?",
    "How do I factorize a quadratic?",
    "What is completing the square?",
    "Solve quadratic using the quadratic formula",
    "What is discriminant?",
    "What does discriminant tell us about roots?",
    "What is a complex number?",
    "What is modulus of a complex number?",
    "What is the argument of a complex number?",
    "How do you solve simultaneous equations?",
    "What is substitution method for simultaneous equations?",
    "What is elimination method?",
    "What are the types of algebraic expressions?",
    "What is a monomial?",
    "What is a binomial?",
    "What is a polynomial?",
    "How do you multiply polynomials?",
    "What is the FOIL method?",
    "How do you factor a difference of squares?",
    "What is a perfect square trinomial?",
    "What is the sum and product of roots?",
    "What is Vieta's formulas?",
    "How do you solve absolute value equations?",
    "What is a rational expression?",
    "How do you simplify rational expressions?",
    "What is direct proportion?",
    "What is inverse proportion?",
    "What is ratio and proportion?",
    "How do you solve ratio problems?",
    "What is a linear inequality?",
    "What is a quadratic inequality?",
    "What is the number line?",
    "How do you graph a linear equation?",
    "What is slope-intercept form?",
    "What is point-slope form?",
    "What is standard form of a linear equation?",
    "What are like terms?",
    "How do you combine like terms?",
    "What is index notation?",
    "What are laws of indices?",
    "What is a power?",
    "What is an exponent?",
    "What is a square root?",
    "What is a cube root?",
    "How do you simplify surds?",
    "What is rationalizing the denominator?",
    "What is an arithmetic sequence?",
    "What is the common difference?",
    "What is a geometric sequence?",
    "What is the common ratio?",
    "What is the nth term formula?",
    "What is the sum of n terms formula?",
    "What is partial fractions?",
    "How do you decompose into partial fractions?",
    "What is long division of polynomials?",
    "What is the remainder theorem?",
    "What is the factor theorem?",
    "What is Pascal's triangle?",
    "How do you expand using binomial theorem?",
    "What is algebraic identity?",
    "What is a plus b whole squared?",
    "What is a minus b whole squared?",
    "What is a squared minus b squared?",
    "What is a cubed plus b cubed?",
    "What is a cubed minus b cubed?",
    "How do you solve word problems in algebra?",
    "What is age problem in algebra?",
    "What is work and time problem?",

    # --- Geometry (60) ---
    "How do I calculate the area of a circle?",
    "What is the Pythagorean theorem?",
    "What is the circumference of a circle?",
    "Area of a triangle formula",
    "Volume of a sphere formula",
    "Area of rectangle",
    "Volume of cylinder",
    "Surface area of cube",
    "Types of angles",
    "Right angle obtuse angle acute angle",
    "Complementary and supplementary angles",
    "What is geometry?",
    "What is a polygon?",
    "What is a quadrilateral?",
    "Properties of a parallelogram",
    "Properties of a rhombus",
    "What is a trapezoid?",
    "What is congruence in geometry?",
    "What is similarity in geometry?",
    "What is a tangent to a circle?",
    "What is a chord?",
    "What is the angle in a semicircle?",
    "What is the exterior angle of a triangle?",
    "Pythagoras theorem proof",
    "What is Heron's formula?",
    "What is area of a sector?",
    "What is arc length?",
    "What is a regular polygon?",
    "Sum of interior angles of a polygon",
    "What is a diagonal?",
    "What is perimeter?",
    "Volume of a cone formula",
    "Surface area of a sphere",
    "Surface area of a cylinder",
    "What is lateral surface area?",
    "What is total surface area?",
    "What is volume?",
    "What is a prism?",
    "What is a pyramid?",
    "Volume of a pyramid formula",
    "What is a triangle?",
    "Types of triangles",
    "What is equilateral triangle?",
    "What is isosceles triangle?",
    "What is scalene triangle?",
    "Sum of angles in a triangle",
    "What is the centroid of a triangle?",
    "What is the circumcenter?",
    "What is the incenter?",
    "What is the orthocenter?",
    "What is Euler's line?",
    "What is a median of a triangle?",
    "What is an altitude of a triangle?",
    "What is an angle bisector?",
    "What is a perpendicular bisector?",
    "What is pi in geometry?",
    "What is a semicircle?",
    "What is a diameter?",
    "What is a radius?",
    "What are concentric circles?",
    "What is the area of an annulus?",

    # --- Coordinate Geometry (30) ---
    "Distance formula",
    "Midpoint formula",
    "Slope of line y equals 3x plus 7",
    "Equation of straight line",
    "What is coordinate geometry?",
    "What is parabola?",
    "What is ellipse?",
    "What is hyperbola?",
    "What is circle equation?",
    "What is the slope of a horizontal line?",
    "What is the slope of a vertical line?",
    "How do you find the equation of a line through two points?",
    "What is the x-intercept?",
    "What is the y-intercept?",
    "What are the four quadrants?",
    "What is the origin in coordinate geometry?",
    "How do you reflect a point across the x-axis?",
    "What is translation in coordinate geometry?",
    "What is rotation in coordinate geometry?",
    "What is dilation?",
    "What is the equation of a circle with center and radius?",
    "How do you find center and radius from circle equation?",
    "What is the focus of a parabola?",
    "What is the directrix of a parabola?",
    "What is the vertex of a parabola?",
    "What is the axis of symmetry?",
    "What is the eccentricity of an ellipse?",
    "What is the foci of an ellipse?",
    "What are asymptotes of a hyperbola?",
    "What is section formula?",

    # --- Calculus (50) ---
    "Calculate the derivative of 3x squared plus 2x minus 5",
    "What is the integral of x squared?",
    "What is calculus?",
    "What is a limit in calculus?",
    "What is continuity?",
    "What is a derivative?",
    "What is integration?",
    "What is definite integral?",
    "What is indefinite integral?",
    "What is differential equation?",
    "How do you differentiate sin x?",
    "How do you differentiate cos x?",
    "How do you differentiate e to the x?",
    "What is the chain rule?",
    "What is the product rule?",
    "What is the quotient rule?",
    "What is integration by parts?",
    "What is substitution in integration?",
    "What is the fundamental theorem of calculus?",
    "What is maxima and minima?",
    "How do you find turning points?",
    "What is a critical point?",
    "What is the second derivative test?",
    "What is implicit differentiation?",
    "What is logarithmic differentiation?",
    "What is the derivative of ln x?",
    "What is the derivative of a to the x?",
    "What is the derivative of tan x?",
    "What is the antiderivative?",
    "What is the area under a curve?",
    "What is a Riemann sum?",
    "What is the trapezoidal rule?",
    "What is Simpson's rule?",
    "What is L'Hopital's rule?",
    "What is a Taylor series?",
    "What is a Maclaurin series?",
    "What is partial differentiation?",
    "What is gradient in calculus?",
    "What is the divergence theorem?",
    "What is a vector function?",
    "What is the rate of change?",
    "How does calculus apply to physics?",
    "What is the velocity as a derivative?",
    "What is acceleration as a second derivative?",
    "What is the integral of velocity?",
    "What is the mean value theorem?",
    "What is Rolle's theorem?",
    "What is continuity vs differentiability?",
    "What is a piecewise function?",
    "What is the limit at infinity?",

    # --- Trigonometry (40) ---
    "Trigonometry basics",
    "Value of sin 90 degrees cos 90 degrees",
    "Convert 45 degrees to radians",
    "What is trigonometric identity?",
    "What is sin squared theta plus cos squared theta?",
    "What is tan theta?",
    "What is cot theta?",
    "What is sec theta?",
    "What is cosec theta?",
    "What is inverse trigonometry?",
    "What is sine rule?",
    "What is cosine rule?",
    "How do you solve trigonometric equations?",
    "What is the unit circle?",
    "What are the trigonometric ratios?",
    "How do I find angles using trigonometry?",
    "What is sin 30 degrees?",
    "What is cos 60 degrees?",
    "What is tan 45 degrees?",
    "What is sin 0 degrees?",
    "What is cos 180 degrees?",
    "What is the double angle formula?",
    "What is the compound angle formula?",
    "What is the half angle formula?",
    "What is the product to sum formula?",
    "What is the sum to product formula?",
    "What is arcsin?",
    "What is arccos?",
    "What is arctan?",
    "What is the graph of sin x?",
    "What is the period of cos x?",
    "What is amplitude in trigonometry?",
    "What is phase shift?",
    "What is frequency in trigonometry?",
    "What are complementary angles in trig?",
    "What is the Pythagorean identity?",
    "What is tan squared theta plus 1?",
    "How do you prove trigonometric identities?",
    "What is SOHCAHTOA?",
    "How do you use trigonometry to find height?",

    # --- Statistics & Probability (40) ---
    "Mean of 10 20 30 40",
    "Probability of heads in coin toss",
    "What is statistics?",
    "Standard deviation",
    "Median mode mean",
    "What is probability distribution?",
    "What is binomial distribution?",
    "What is normal distribution?",
    "What is hypothesis testing?",
    "What is correlation?",
    "What is regression?",
    "What is linear regression?",
    "What is variance?",
    "What is range in statistics?",
    "What is cumulative frequency?",
    "How do you draw a histogram?",
    "What is a bar chart?",
    "What is a pie chart?",
    "What is sample and population in statistics?",
    "What is the difference between mean and median?",
    "When do we use mode?",
    "What is interquartile range?",
    "What is a box plot?",
    "What is a scatter graph?",
    "What is Bayes theorem?",
    "What is conditional probability?",
    "What is independent events in probability?",
    "What is mutually exclusive events?",
    "What is the addition rule in probability?",
    "What is the multiplication rule in probability?",
    "What is a sample space?",
    "What is an event in probability?",
    "What is probability of complementary events?",
    "What is expected value?",
    "What is a tree diagram in probability?",
    "What is relative frequency?",
    "What is theoretical probability?",
    "What is experimental probability?",
    "What is a Venn diagram in probability?",
    "What is the Poisson distribution?",

    # --- Number Theory (30) ---
    "What is a prime number?",
    "LCM and HCF",
    "HCF of 12 and 18",
    "What is a rational number?",
    "What is an irrational number?",
    "What is number system?",
    "What is factorial of 5?",
    "What is value of pi?",
    "What is Euclid's division algorithm?",
    "What is divisibility rule?",
    "What are factors of a number?",
    "What are multiples of a number?",
    "What is a composite number?",
    "What is a co-prime number?",
    "What is a perfect number?",
    "What is prime factorization?",
    "What is the Sieve of Eratosthenes?",
    "What is the fundamental theorem of arithmetic?",
    "What is modular arithmetic?",
    "What is a remainder theorem?",
    "What is Fermat's little theorem?",
    "What is Euler's totient function?",
    "What is a real number?",
    "What is an integer?",
    "What is a whole number?",
    "What is a natural number?",
    "What is the number line?",
    "What is absolute value?",
    "What is a recurring decimal?",
    "How do you convert fraction to decimal?",

    # --- Matrices, Vectors, Sets (40) ---
    "What is a matrix?",
    "Determinant of 2x2 matrix",
    "What is matrix multiplication?",
    "What is transpose of matrix?",
    "What is inverse of matrix?",
    "What is eigenvalue?",
    "What is eigenvector?",
    "What is linear algebra?",
    "What is a vector in math?",
    "What is scalar triple product?",
    "What is set theory?",
    "Venn diagram",
    "What is union and intersection of sets?",
    "Difference between permutation and combination",
    "How many ways can you arrange 5 objects?",
    "What is a null matrix?",
    "What is an identity matrix?",
    "What is a square matrix?",
    "What is a diagonal matrix?",
    "What is a symmetric matrix?",
    "What is rank of a matrix?",
    "What is row echelon form?",
    "What is Gaussian elimination?",
    "What is Cramer's rule?",
    "What is a system of linear equations?",
    "What is a consistent system?",
    "What is an inconsistent system?",
    "What is a power set?",
    "What is a subset?",
    "What is a universal set?",
    "What is complement of a set?",
    "What is De Morgan's law?",
    "What is Cartesian product of sets?",
    "What is a relation in math?",
    "What is an equivalence relation?",
    "What is the dot product of vectors?",
    "What is the cross product of vectors?",
    "What is the magnitude of a vector?",
    "What is a position vector?",
    "What is collinear vectors?",

    # --- Finance & Misc (30) ---
    "What is 25 percent of 400?",
    "Simple interest formula",
    "Compound interest formula",
    "How do you calculate percentage?",
    "What is percentage increase?",
    "What is profit and loss?",
    "What is 15 percent of 200?",
    "What is discount?",
    "What is markup?",
    "What is sales tax?",
    "How do you calculate compound interest annually?",
    "How do you calculate simple interest for 3 years?",
    "What is time value of money?",
    "What is logarithm?",
    "Solve log x equals 2",
    "What is natural log?",
    "Laws of logarithms",
    "Change of base formula",
    "What is a function?",
    "Domain and range of a function",
    "What is an exponential function?",
    "What is a logarithmic function?",
    "What is a composite function?",
    "What is an inverse function?",
    "What is even and odd function?",
    "What is a bijective function?",
    "What is the Fibonacci sequence?",
    "What is the golden ratio?",
    "What is mathematical induction?",
    "What is proof by contradiction?",
]

# ==============================================================================
# CHEMISTRY - 600 questions
# ==============================================================================
chemistry = [
    # --- Atomic Structure (40) ---
    "Difference between atom and molecule",
    "What are isotopes?",
    "What is atomic structure?",
    "What is Bohr model of atom?",
    "What is electron configuration?",
    "What are subatomic particles?",
    "What is proton neutron electron?",
    "What is nucleus of an atom?",
    "What is orbital in chemistry?",
    "What is quantum number?",
    "What is atomic number?",
    "What is atomic mass?",
    "What is an ion?",
    "What is a cation?",
    "What is an anion?",
    "What is ionization energy?",
    "What is electron affinity?",
    "What is atomic radius?",
    "What is nuclear charge?",
    "What is shielding effect?",
    "What is the aufbau principle?",
    "What is Hund's rule?",
    "What is Pauli exclusion principle?",
    "What is s p d f orbital?",
    "What is valence electron?",
    "What is an excited state of an atom?",
    "What is ground state of an atom?",
    "What is emission spectrum?",
    "What is absorption spectrum?",
    "What is the hydrogen spectrum?",
    "What is Balmer series?",
    "What is Lyman series?",
    "How many electrons can each shell hold?",
    "What is the octet rule?",
    "What is isoelectronic species?",
    "What is isobar?",
    "What is isotone?",
    "What is the difference between isotope and isobar?",
    "What is mass number?",
    "What is molar mass?",

    # --- Periodic Table (30) ---
    "Explain the periodic table",
    "Modern periodic law",
    "What is an element?",
    "What is a period in the periodic table?",
    "What is a group in the periodic table?",
    "What are noble gases?",
    "What are halogens?",
    "What are alkali metals?",
    "What are alkaline earth metals?",
    "What are transition metals?",
    "What is the most abundant element on earth?",
    "What is atomic number of carbon?",
    "What is Mendeleev's contribution?",
    "What are lanthanides?",
    "What are actinides?",
    "What is periodicity in chemistry?",
    "What is the trend in atomic radius across period?",
    "What is the trend in ionization energy across period?",
    "What is the trend in electronegativity down a group?",
    "What is the most electronegative element?",
    "What is the most reactive metal?",
    "What is the most reactive non-metal?",
    "What is the lightest element?",
    "What is the heaviest natural element?",
    "Where is hydrogen placed in periodic table?",
    "What is a metalloid?",
    "What are p-block elements?",
    "What are s-block elements?",
    "What are d-block elements?",
    "What are f-block elements?",

    # --- Chemical Bonding (40) ---
    "Explain ionic and covalent bonding",
    "What is a covalent bond?",
    "What is an ionic bond?",
    "What is a metallic bond?",
    "What is hydrogen bonding?",
    "What is a polar covalent bond?",
    "What is electronegativity?",
    "What is valency?",
    "What is Lewis structure?",
    "What is VSEPR theory?",
    "What is hybridization in chemistry?",
    "What is sp hybridization?",
    "What is sp2 hybridization?",
    "What is sp3 hybridization?",
    "What is a sigma bond?",
    "What is a pi bond?",
    "What is bond length?",
    "What is bond energy?",
    "What is bond angle?",
    "What is intermolecular force?",
    "What is van der Waals force?",
    "What is London dispersion force?",
    "What is dipole-dipole interaction?",
    "What is ionic radius?",
    "What is lattice energy?",
    "What is Born-Haber cycle?",
    "What is coordinate bond?",
    "What is dative bond?",
    "What is a double bond?",
    "What is a triple bond?",
    "What is resonance in chemistry?",
    "What is delocalization of electrons?",
    "What is molecular geometry?",
    "What is VSEPR for water?",
    "What is shape of ammonia?",
    "What is shape of methane?",
    "What is polarity of a molecule?",
    "What is a non-polar molecule?",
    "What is dipole moment?",
    "What is electrovalent bond?",

    # --- Chemical Reactions & Stoichiometry (50) ---
    "Types of chemical reactions",
    "Balance H2 plus O2 gives H2O",
    "What is a chemical equation?",
    "What is balancing a chemical equation?",
    "What is combination reaction?",
    "What is decomposition reaction?",
    "What is displacement reaction?",
    "What is double displacement reaction?",
    "What is precipitation reaction?",
    "What is combustion reaction?",
    "What is exothermic reaction?",
    "What is endothermic reaction?",
    "What is Avogadro's number?",
    "What is a mole?",
    "What is stoichiometry?",
    "How do you calculate moles?",
    "What is molarity?",
    "What is molality?",
    "Empirical and molecular formula",
    "What is percentage composition?",
    "What is limiting reagent?",
    "What is excess reagent?",
    "What is theoretical yield?",
    "What is actual yield?",
    "What is percentage yield?",
    "What is mole ratio?",
    "What is a mole fraction?",
    "What is normality?",
    "What is equivalent weight?",
    "What is dilution formula?",
    "How do you prepare a standard solution?",
    "What is concentration in moles per litre?",
    "What is parts per million?",
    "What is a solution in chemistry?",
    "What is solute and solvent?",
    "What is mass fraction?",
    "What is volume fraction?",
    "What is ppm?",
    "How do you calculate molar mass from formula?",
    "What is formula mass?",
    "What is relative molecular mass?",
    "What is gram atomic mass?",
    "What is gram molecular mass?",
    "What is gram equivalent?",
    "How do you calculate empirical formula from percentages?",
    "What is molecular formula from empirical formula?",
    "What is conservation of mass in reactions?",
    "What is mass balance?",
    "What is charge balance?",
    "What is atom economy?",

    # --- Acids, Bases & pH (30) ---
    "What happens when acid reacts with base?",
    "What is the pH scale?",
    "What is an acid?",
    "What is a base?",
    "What is a neutral solution?",
    "What is neutralization reaction?",
    "Strong acid vs weak acid",
    "What is Arrhenius acid?",
    "What is Bronsted Lowry acid?",
    "What is pH of blood?",
    "What is litmus paper?",
    "What is pOH?",
    "What is the relationship between pH and pOH?",
    "What is a buffer solution?",
    "How does a buffer work?",
    "What is Henderson-Hasselbalch equation?",
    "What is Ka?",
    "What is Kb?",
    "What is Kw?",
    "What is degree of dissociation?",
    "What is hydrolysis of salt?",
    "What is a salt?",
    "What is an acidic salt?",
    "What is a basic salt?",
    "What is a normal salt?",
    "What is pH of HCl?",
    "What is pH of NaOH?",
    "What is Lewis acid?",
    "What is Lewis base?",
    "What is amphoteric substance?",

    # --- Gases (20) ---
    "Boyle's law",
    "Charles law",
    "Ideal gas equation",
    "What is Avogadro's law?",
    "What is Gay-Lussac's law?",
    "What is Dalton's law of partial pressure?",
    "What is kinetic molecular theory?",
    "What is diffusion?",
    "What is effusion?",
    "What is Graham's law?",
    "What is real gas?",
    "What is ideal gas?",
    "What is van der Waals equation?",
    "What is compressibility factor?",
    "What is root mean square speed?",
    "What is average kinetic energy of gas?",
    "What is STP in chemistry?",
    "What is molar volume at STP?",
    "What is partial pressure?",
    "What is vapour pressure?",

    # --- Redox & Electrochemistry (30) ---
    "Oxidation and reduction",
    "Redox reaction examples",
    "What is electrolysis?",
    "What is electrochemical cell?",
    "What is galvanic cell?",
    "What is oxidation state?",
    "What is oxidizing agent?",
    "What is reducing agent?",
    "What is electrolyte?",
    "What is electrode?",
    "What is anode and cathode?",
    "What is EMF of a cell?",
    "What is standard electrode potential?",
    "What is the electrochemical series?",
    "What is Faraday's first law of electrolysis?",
    "What is Faraday's second law of electrolysis?",
    "What is electrolytic cell?",
    "What is electroplating?",
    "What is corrosion?",
    "What is rusting of iron?",
    "How does galvanization prevent rusting?",
    "What is cathodic protection?",
    "What is a fuel cell?",
    "What is the Daniell cell?",
    "What is Nernst equation?",
    "What is a salt bridge?",
    "What is reduction potential?",
    "What is oxidation potential?",
    "What is balancing redox reactions?",
    "What is the half-reaction method?",

    # --- Equilibrium & Kinetics (30) ---
    "What is a catalyst?",
    "Le Chatelier's principle",
    "Chemical equilibrium",
    "What is rate of reaction?",
    "What affects rate of reaction?",
    "What is activation energy?",
    "What is reaction rate constant?",
    "What is order of reaction?",
    "What is equilibrium constant?",
    "What is Kp and Kc?",
    "What is dynamic equilibrium?",
    "What is homogeneous equilibrium?",
    "What is heterogeneous equilibrium?",
    "What is the effect of temperature on equilibrium?",
    "What is the effect of pressure on equilibrium?",
    "What is the effect of concentration on equilibrium?",
    "What is Arrhenius equation?",
    "What is pre-exponential factor?",
    "What is collision theory?",
    "What is transition state theory?",
    "What is zero order reaction?",
    "What is first order reaction?",
    "What is second order reaction?",
    "What is half-life in kinetics?",
    "What is integrated rate law?",
    "What is reaction mechanism?",
    "What is rate determining step?",
    "What is a catalyst and how does it work?",
    "What is autocatalysis?",
    "What is photocatalysis?",

    # --- Organic Chemistry (80) ---
    "What are hydrocarbons?",
    "What is Bakelite?",
    "Fractional distillation of petroleum",
    "Soap and detergent",
    "Esterification reaction",
    "Saponification",
    "What is polymer?",
    "What is organic chemistry?",
    "What is functional group?",
    "What is isomer?",
    "What is alkane alkene alkyne?",
    "What is benzene?",
    "What is alcohol in chemistry?",
    "What is carboxylic acid?",
    "What is aldehyde?",
    "What is ketone?",
    "What is ester?",
    "What is addition reaction?",
    "What is substitution reaction?",
    "What is polymerization?",
    "What is nylon?",
    "What is PVC?",
    "What is ethanol?",
    "What is methanol?",
    "What is glucose?",
    "What is sucrose?",
    "What is starch?",
    "What is cellulose?",
    "What is protein?",
    "What is amino acid?",
    "What is DNA in chemistry?",
    "What is nucleotide?",
    "What is a fat?",
    "What is a lipid?",
    "What is a carbohydrate?",
    "What is fermentation?",
    "What is vulcanization?",
    "What is cracking of petroleum?",
    "What is refining of petroleum?",
    "What is petrochemical?",
    "What is natural gas?",
    "What is LPG?",
    "What is CNG?",
    "What is biodiesel?",
    "What is ethylene?",
    "What is propene?",
    "What is IUPAC naming?",
    "How do you name organic compounds?",
    "What is structural formula?",
    "What is displayed formula?",
    "What is homologous series?",
    "What is general formula of alkanes?",
    "What is general formula of alkenes?",
    "What is combustion of hydrocarbons?",
    "What is halogenation?",
    "What is nitration of benzene?",
    "What is sulfonation?",
    "What is Friedel-Crafts reaction?",
    "What is Grignard reagent?",
    "What is elimination reaction?",
    "What is condensation reaction?",
    "What is hydrolysis in organic chemistry?",
    "What is oxidation of alcohols?",
    "What is reduction of carbonyl compounds?",
    "What is a primary alcohol?",
    "What is a secondary alcohol?",
    "What is a tertiary alcohol?",
    "What is dehydration of alcohol?",
    "What is nucleophilic substitution?",
    "What is electrophilic addition?",
    "What is Markovnikov's rule?",
    "What is Zaitsev's rule?",
    "What is geometric isomerism?",
    "What is optical isomerism?",
    "What is chirality?",
    "What is enantiomer?",
    "What is a racemic mixture?",

    # --- Thermochemistry & Misc (50) ---
    "What is enthalpy?",
    "What is Hess's law?",
    "What is heat of combustion?",
    "What is heat of formation?",
    "What is heat of neutralization?",
    "What is heat of solution?",
    "What is bond enthalpy?",
    "What is calorimetry?",
    "What is lattice enthalpy?",
    "What is Born-Haber cycle in thermochemistry?",
    "What is endothermic vs exothermic?",
    "What is entropy in chemistry?",
    "What is Gibbs free energy?",
    "What is spontaneous reaction?",
    "What is equilibrium in terms of Gibbs energy?",
    "What is chromatography?",
    "What is distillation?",
    "What is filtration?",
    "What is crystallization?",
    "What is titration?",
    "What is indicator in chemistry?",
    "What is universal indicator?",
    "What is flame test?",
    "What is qualitative analysis?",
    "What is quantitative analysis?",
    "What is spectroscopy?",
    "What is mass spectrometry?",
    "What is NMR spectroscopy?",
    "What is IR spectroscopy?",
    "What is paper chromatography?",
    "What is column chromatography?",
    "What is thin layer chromatography?",
    "What is gravimetric analysis?",
    "What is volumetric analysis?",
    "What is back titration?",
    "What is water hardness?",
    "What is permanent hardness?",
    "What is temporary hardness?",
    "How do you remove hardness from water?",
    "What is water treatment?",
    "What is water pollution?",
    "What is air pollution?",
    "What causes acid rain?",
    "What is ozone depletion?",
    "What is CFC?",
    "What is greenhouse gas?",
    "What is carbon dating?",
    "What is radioactive decay?",
    "What is nuclear fission in chemistry?",
    "What is metallurgy?",
]

# ==============================================================================
# COMPUTER SCIENCE - 600 questions
# ==============================================================================
cs = [
    # --- Programming Basics (60) ---
    "Write a Python program to print hello world",
    "How do I declare a variable in Python?",
    "What is a loop in programming?",
    "How does if-else statement work?",
    "What is a function in programming?",
    "What is a programming language?",
    "What is debugging?",
    "What is an IDE?",
    "What is pseudocode?",
    "What is flowchart?",
    "What is syntax error?",
    "What is runtime error?",
    "What is logic error?",
    "What is a comment in code?",
    "What is indentation in Python?",
    "What is a for loop?",
    "What is a while loop?",
    "What is break and continue?",
    "What is a nested loop?",
    "What is an array?",
    "What is a list in Python?",
    "What is a tuple in Python?",
    "What is a dictionary in Python?",
    "What is a set in Python?",
    "What is string in programming?",
    "How do you concatenate strings?",
    "What is string slicing?",
    "What is type casting?",
    "What is input and output in programming?",
    "What is a constant in programming?",
    "What is a data type?",
    "What is integer data type?",
    "What is float data type?",
    "What is boolean data type?",
    "What is char data type?",
    "What is null in programming?",
    "What is undefined in programming?",
    "What is a scope of a variable?",
    "What is local variable?",
    "What is global variable?",
    "What is pass by value?",
    "What is pass by reference?",
    "What is a lambda function?",
    "What is a default parameter?",
    "What is variable argument in function?",
    "What is a return statement?",
    "What is recursion in programming?",
    "What is base case in recursion?",
    "What is stack overflow?",
    "What is memoization?",
    "What is dynamic programming?",
    "What is a module in Python?",
    "What is a package in Python?",
    "What is import in Python?",
    "What is pip in Python?",
    "What is exception handling?",
    "What is try-except in Python?",
    "What is finally in exception handling?",
    "What is a custom exception?",
    "What is debugging techniques?",

    # --- OOP (40) ---
    "Explain object oriented programming",
    "What is a class?",
    "What is an object?",
    "What is inheritance?",
    "What is polymorphism?",
    "What is encapsulation?",
    "What is abstraction?",
    "What is constructor?",
    "What is method in OOP?",
    "What is instance variable?",
    "What is class variable?",
    "What is method overriding?",
    "What is method overloading?",
    "What is interface?",
    "What is abstract class?",
    "What is multiple inheritance?",
    "What is single inheritance?",
    "What is multilevel inheritance?",
    "What is hierarchical inheritance?",
    "What is super keyword?",
    "What is self in Python?",
    "What is this keyword?",
    "What is a destructor?",
    "What is operator overloading?",
    "What is a static method?",
    "What is a class method?",
    "What is a property in OOP?",
    "What is getter and setter?",
    "What is access modifier?",
    "What is public private protected?",
    "What is composition in OOP?",
    "What is aggregation in OOP?",
    "What is association in OOP?",
    "What is coupling in OOP?",
    "What is cohesion in OOP?",
    "What is SOLID principles?",
    "What is single responsibility principle?",
    "What is open closed principle?",
    "What is DRY principle?",
    "What is design pattern?",

    # --- Data Structures & Algorithms (80) ---
    "What is an algorithm?",
    "What is data structure?",
    "Stack and Queue",
    "Linked list",
    "Binary tree",
    "Graph data structure",
    "Sorting algorithms",
    "Bubble sort explanation",
    "Merge sort",
    "Time complexity",
    "Big O notation",
    "What is binary search?",
    "What is linear search?",
    "What is recursion?",
    "What is greedy algorithm?",
    "What is hash table?",
    "What is a heap?",
    "What is a priority queue?",
    "What is depth first search?",
    "What is breadth first search?",
    "What is quick sort?",
    "What is insertion sort?",
    "What is selection sort?",
    "Space complexity",
    "Best case average case worst case",
    "What is amortized complexity?",
    "What is O of n log n?",
    "What is O of n squared?",
    "What is constant time complexity?",
    "What is a doubly linked list?",
    "What is circular linked list?",
    "What is a binary search tree?",
    "What is AVL tree?",
    "What is a red-black tree?",
    "What is a trie?",
    "What is a segment tree?",
    "What is a Fenwick tree?",
    "What is a deque?",
    "What is an adjacency matrix?",
    "What is an adjacency list?",
    "What is Dijkstra's algorithm?",
    "What is Bellman-Ford algorithm?",
    "What is Floyd-Warshall algorithm?",
    "What is Kruskal's algorithm?",
    "What is Prim's algorithm?",
    "What is topological sort?",
    "What is a spanning tree?",
    "What is minimum spanning tree?",
    "What is dynamic programming vs recursion?",
    "What is the knapsack problem?",
    "What is the longest common subsequence?",
    "What is the travelling salesman problem?",
    "What is backtracking?",
    "What is branch and bound?",
    "What is divide and conquer?",
    "What is memoization vs tabulation?",
    "What is a hash function?",
    "What is hash collision?",
    "What is open addressing?",
    "What is chaining in hash table?",
    "What is radix sort?",
    "What is counting sort?",
    "What is heap sort?",
    "What is the difference between stack and queue?",
    "What is infix postfix prefix notation?",
    "What is expression tree?",
    "What is level order traversal?",
    "What is inorder traversal?",
    "What is preorder traversal?",
    "What is postorder traversal?",
    "What is graph coloring?",
    "What is the N-queens problem?",
    "What is Floyd's cycle detection?",
    "What is two pointer technique?",
    "What is sliding window?",
    "What is binary lifting?",

    # --- Hardware & OS (50) ---
    "Difference between RAM and ROM",
    "What is CPU?",
    "Explain CPU and its components",
    "Primary memory vs secondary memory",
    "What is hard drive?",
    "What is SSD?",
    "What is motherboard?",
    "What is GPU?",
    "What is cache memory?",
    "What is register?",
    "What is ALU?",
    "What is control unit?",
    "What is fetch decode execute cycle?",
    "What is clock speed?",
    "What is bit and byte?",
    "What is an operating system?",
    "What is process in OS?",
    "What is thread?",
    "What is multithreading?",
    "What is deadlock?",
    "What is virtual memory?",
    "What is paging?",
    "What is file system?",
    "What is shell?",
    "What is kernel?",
    "What is Linux?",
    "What is process scheduling?",
    "What is context switching?",
    "What is semaphore?",
    "What is mutex?",
    "What is race condition?",
    "What is critical section?",
    "What is memory management?",
    "What is garbage collection?",
    "What is BIOS?",
    "What is bootloader?",
    "What is firmware?",
    "What is driver in OS?",
    "What is interrupt?",
    "What is system call?",
    "What is RAID?",
    "What is partitioning a disk?",
    "What is a file in computing?",
    "What is a directory?",
    "What is a path in computing?",
    "What is permission in Linux?",
    "What is chmod?",
    "What is process management?",
    "What is swapping in OS?",
    "What is thrashing?",

    # --- Databases (40) ---
    "What is a database?",
    "What is SQL?",
    "What is primary key?",
    "What is foreign key?",
    "What is normalization?",
    "What is a relational database?",
    "What is NoSQL?",
    "What is JOIN in SQL?",
    "What is SELECT statement?",
    "What is WHERE clause?",
    "What is INDEX in database?",
    "What is ACID in database?",
    "What is MongoDB?",
    "What is transaction in database?",
    "What is INNER JOIN?",
    "What is LEFT JOIN?",
    "What is RIGHT JOIN?",
    "What is FULL OUTER JOIN?",
    "What is GROUP BY in SQL?",
    "What is ORDER BY in SQL?",
    "What is HAVING in SQL?",
    "What is aggregate function in SQL?",
    "What is COUNT in SQL?",
    "What is SUM AVG MIN MAX in SQL?",
    "What is a view in SQL?",
    "What is a stored procedure?",
    "What is a trigger in database?",
    "What is denormalization?",
    "What is first normal form?",
    "What is second normal form?",
    "What is third normal form?",
    "What is BCNF?",
    "What is entity relationship diagram?",
    "What is schema in database?",
    "What is a cursor in SQL?",
    "What is subquery in SQL?",
    "What is a composite key?",
    "What is referential integrity?",
    "What is cascade delete?",
    "What is database sharding?",

    # --- Networking (40) ---
    "TCP IP model",
    "What is DNS?",
    "What is IP address?",
    "What is MAC address?",
    "What is subnetting?",
    "What is VPN?",
    "What is firewall?",
    "HTTP vs HTTPS",
    "What is a web server?",
    "What is bandwidth?",
    "What is latency?",
    "What is OSI model?",
    "What is router?",
    "What is protocol?",
    "What is TCP vs UDP?",
    "What is port number?",
    "What is socket programming?",
    "What is NAT?",
    "What is DHCP?",
    "What is ARP?",
    "What is ICMP?",
    "What is ping?",
    "What is traceroute?",
    "What is load balancing?",
    "What is CDN?",
    "What is a proxy server?",
    "What is a hub vs switch?",
    "What is full duplex vs half duplex?",
    "What is wireless networking?",
    "What is WiFi protocol?",
    "What is Bluetooth?",
    "What is a packet?",
    "What is packet switching?",
    "What is circuit switching?",
    "What is network topology?",
    "What is star topology?",
    "What is bus topology?",
    "What is mesh topology?",
    "What is LAN WAN MAN?",
    "What is IPv4 vs IPv6?",

    # --- Web, AI & Emerging Tech (80) ---
    "Frontend vs backend",
    "What is HTML used for?",
    "What is CSS?",
    "What is JavaScript?",
    "What is an API?",
    "What is JSON?",
    "What is XML?",
    "What is REST API?",
    "What is GraphQL?",
    "What is flask?",
    "What is django?",
    "What is react.js?",
    "What is node.js?",
    "What is Docker?",
    "What is Kubernetes?",
    "What is microservices?",
    "What is monolithic architecture?",
    "Git and GitHub",
    "Version control system",
    "What is agile methodology?",
    "What is scrum?",
    "What is SDLC?",
    "What is software testing?",
    "What is unit testing?",
    "Machine learning basics",
    "Artificial intelligence basics",
    "Difference between AI and ML",
    "What is neural network?",
    "What is deep learning?",
    "What is computer vision?",
    "What is natural language processing?",
    "What is reinforcement learning?",
    "What is supervised learning?",
    "What is unsupervised learning?",
    "What is overfitting?",
    "What is underfitting?",
    "What is feature engineering?",
    "What is data preprocessing?",
    "What is pandas in Python?",
    "What is numpy?",
    "What is matplotlib?",
    "What is scikit-learn?",
    "Cybersecurity basics",
    "What is phishing?",
    "Virus vs Worm",
    "What is malware?",
    "What is ransomware?",
    "What is encryption?",
    "What is hashing?",
    "What is SSL certificate?",
    "What is two factor authentication?",
    "What is SQL injection?",
    "Cloud computing",
    "What is AWS?",
    "Big data",
    "What is Hadoop?",
    "Blockchain technology",
    "Cryptocurrency",
    "What is IoT?",
    "What is 5G?",
    "What is edge computing?",
    "What is quantum computing?",
    "What is augmented reality?",
    "What is virtual reality?",
    "Uses of Python",
    "Uses of Java",
    "What is C++?",
    "What is C programming?",
    "Difference between Python and Java",
    "What is TypeScript?",
    "What is Kotlin?",
    "What is continuous integration?",
    "What is continuous deployment?",
    "What is DevOps?",
    "What is serverless architecture?",
    "What is a webhook?",
    "What is WebSocket?",
    "What is CORS?",
    "What is OAuth?",
    "What is JWT token?",
    "What is API key?",

    # --- Misc CS (10) ---
    "What is compiler?",
    "What is interpreter?",
    "What is assembler?",
    "What is machine code?",
    "What is binary code?",
    "What is ASCII?",
    "What is Unicode?",
    "What is hexadecimal?",
    "What is binary to decimal conversion?",
    "What is octal number system?",
]

# ==============================================================================
# ENGLISH - 600 questions
# ==============================================================================
english = [
    # --- Grammar (100) ---
    "Why is grammar important in English?",
    "Difference between there and their",
    "Difference between noun and verb",
    "Correct the sentence He go to school yesterday",
    "Active and passive voice",
    "What is a preposition?",
    "Direct and indirect speech",
    "What is a conjunction?",
    "What is an adjective?",
    "What is an adverb?",
    "Who vs Whom",
    "Correct She is more taller than me",
    "Subject verb agreement",
    "Tenses in English",
    "Present perfect tense",
    "Future continuous tense",
    "Punctuation marks",
    "Use of comma",
    "Question tag",
    "Reported speech",
    "Conditional sentences",
    "Zero conditional",
    "First conditional",
    "Second conditional",
    "Third conditional",
    "Modal verbs",
    "Should vs Must",
    "What is a clause?",
    "What is a phrase?",
    "What is a sentence?",
    "Simple compound and complex sentence",
    "What is a subordinate clause?",
    "What is a relative clause?",
    "What is a noun clause?",
    "What is an adverbial clause?",
    "What is subject in a sentence?",
    "What is predicate?",
    "What is object in grammar?",
    "What is a gerund?",
    "What is an infinitive?",
    "What is a participle?",
    "What is a dangling modifier?",
    "What is the Oxford comma?",
    "How to use semicolon?",
    "How to use colon?",
    "When to use apostrophe?",
    "Its vs It's",
    "Your vs You're",
    "They're vs Their vs There",
    "Then vs Than",
    "Affect vs Effect",
    "Fewer vs Less",
    "Lie vs Lay",
    "Passed vs Past",
    "Principal vs Principle",
    "Complement vs Compliment",
    "Disinterested vs Uninterested",
    "Imply vs Infer",
    "Nauseous vs Nauseated",
    "Who's vs Whose",
    "Accept vs Except",
    "Loose vs Lose",
    "Bring vs Take",
    "Sit vs Set",
    "Rise vs Raise",
    "Further vs Farther",
    "May vs Might",
    "Can vs May",
    "Will vs Shall",
    "Could vs Would",
    "What is the past perfect tense?",
    "What is the present continuous tense?",
    "What is the future perfect tense?",
    "What is the simple past tense?",
    "What is the simple future tense?",
    "What is passive voice construction?",
    "How do you convert active to passive voice?",
    "What is subject-verb inversion?",
    "What is ellipsis in grammar?",
    "What is a cleft sentence?",
    "What is emphasis in English grammar?",
    "What are articles in English?",
    "When to use definite article?",
    "When to use indefinite article?",
    "What is a quantifier?",
    "What is a determiner?",
    "What are demonstrative adjectives?",
    "What are possessive adjectives?",
    "What are interrogative pronouns?",
    "What are indefinite pronouns?",
    "What is a reflexive pronoun?",
    "What is a relative pronoun?",
    "What is a collective noun?",
    "What is an abstract noun?",
    "What is a concrete noun?",
    "What is a proper noun?",
    "What is a common noun?",
    "What is a countable noun?",
    "What is an uncountable noun?",
    "What are irregular plurals?",

    # --- Vocabulary (60) ---
    "Synonym for beautiful",
    "Antonym for difficult",
    "Meaning of ubiquitous",
    "What is a homophone?",
    "What is a synonym?",
    "What is an antonym?",
    "What is a homonym?",
    "What is a palindrome?",
    "What is an acronym?",
    "What is an abbreviation?",
    "What is a suffix?",
    "What is a prefix?",
    "Root word examples",
    "What is etymology?",
    "What is a portmanteau word?",
    "Synonym for happy",
    "Synonym for sad",
    "Synonym for big",
    "Antonym for brave",
    "What is vocabulary?",
    "How to improve vocabulary?",
    "What is a compound word?",
    "What is an idiom?",
    "Meaning of break down",
    "Lend vs Borrow",
    "Meaning of bite the bullet",
    "Meaning of kick the bucket",
    "Meaning of spill the beans",
    "Meaning of hit the nail on the head",
    "Meaning of under the weather",
    "Meaning of once in a blue moon",
    "Meaning of cost an arm and a leg",
    "Meaning of break a leg",
    "Meaning of the ball is in your court",
    "Meaning of burning the midnight oil",
    "What is a euphemism?",
    "What is colloquial language?",
    "What is slang?",
    "What is jargon?",
    "What is a cliche?",
    "What is a neologism?",
    "What is a loanword?",
    "What is denotation?",
    "What is connotation?",
    "What is a taboo word?",
    "What is formal vocabulary?",
    "What is informal vocabulary?",
    "What is technical vocabulary?",
    "What is academic vocabulary?",
    "What is word formation?",
    "What is derivation in vocabulary?",
    "What is inflection in grammar?",
    "What is a false friend in language?",
    "What is a homograph?",
    "What is polysemy?",
    "What is a lexeme?",
    "What is a morpheme?",
    "What is a phoneme?",
    "What is a syllable?",
    "What is stress in spoken English?",

    # --- Figures of Speech & Literary Devices (60) ---
    "Explain simile and metaphor",
    "What is a proverb?",
    "Idiom with example",
    "Alliteration",
    "Personification",
    "Hyperbole",
    "Onomatopoeia",
    "What is symbolism?",
    "What is irony?",
    "What is satire?",
    "What is oxymoron?",
    "What is euphemism in literature?",
    "What is paradox?",
    "What is rhetoric?",
    "What is foreshadowing?",
    "What is flashback in literature?",
    "What is allegory?",
    "What is allusion?",
    "What is anaphora?",
    "What is assonance?",
    "What is consonance?",
    "What is juxtaposition?",
    "What is sarcasm?",
    "What is understatement?",
    "What is imagery in literature?",
    "What is tone in writing?",
    "What is mood in literature?",
    "What is voice in writing?",
    "What is apostrophe as a literary device?",
    "What is chiasmus?",
    "What is antithesis?",
    "What is synecdoche?",
    "What is metonymy?",
    "What is litotes?",
    "What is transferred epithet?",
    "What is pathetic fallacy?",
    "What is dramatic irony?",
    "What is verbal irony?",
    "What is situational irony?",
    "What is a foil character?",
    "What is comic relief?",
    "What is deus ex machina?",
    "What is in medias res?",
    "What is an epigraph?",
    "What is an epilogue?",
    "What is a prologue?",
    "What is leitmotif?",
    "What is stream of consciousness?",
    "What is magical realism?",
    "What is unreliable narrator?",
    "What is suspense in literature?",
    "What is conflict in literature?",
    "What is internal conflict?",
    "What is external conflict?",
    "What is man vs nature conflict?",
    "What is man vs society conflict?",
    "What is rising action?",
    "What is falling action?",
    "What is denouement?",
    "What is catharsis?",

    # --- Writing Skills (60) ---
    "How to write a formal email?",
    "How to write a letter",
    "Narrative essay",
    "Descriptive writing",
    "Thesis statement",
    "Topic sentence",
    "Coherence in writing",
    "Formal vs informal language",
    "How to write an essay introduction?",
    "How to write a conclusion?",
    "What is a paragraph?",
    "What is a body paragraph?",
    "How do you write a persuasive essay?",
    "How do you write an argumentative essay?",
    "What is expository writing?",
    "What is a cover letter?",
    "How to write a resume?",
    "What is a summary?",
    "How do you paraphrase?",
    "What is citation?",
    "What is plagiarism?",
    "What is proofreading?",
    "What is editing?",
    "What is drafting?",
    "What is a hook in essay writing?",
    "What is a transition in writing?",
    "What is unity in a paragraph?",
    "What is coherence in a paragraph?",
    "What is a counter-argument?",
    "How do you write a rebuttal?",
    "What is a research paper?",
    "How do you write a bibliography?",
    "What is APA format?",
    "What is MLA format?",
    "What is a footnote?",
    "What is an appendix in a report?",
    "How do you write a report?",
    "What is an abstract in a paper?",
    "What is technical writing?",
    "What is creative writing?",
    "What is journalistic writing?",
    "What is a news article structure?",
    "What is the inverted pyramid structure?",
    "What is a diary entry?",
    "How do you write a speech?",
    "What is audience awareness in writing?",
    "What is register in writing?",
    "What is style in writing?",
    "How do you develop ideas in writing?",
    "What is brainstorming?",
    "What is mind mapping?",
    "What is outlining an essay?",
    "What is revision in writing?",
    "What is peer review?",
    "How do you improve writing skills?",
    "What is a simile in writing?",
    "What is word choice in writing?",
    "What is sentence variety?",
    "What is show don't tell?",
    "What is active voice in writing?",

    # --- Literature (80) ---
    "What is literature?",
    "What is poetry?",
    "What is prose?",
    "What is drama?",
    "What is fiction vs non-fiction?",
    "What is biography?",
    "What is autobiography?",
    "What is a novel?",
    "What is a short story?",
    "What is a character sketch?",
    "What is plot?",
    "What is climax?",
    "What is theme?",
    "What is genre in literature?",
    "What is tragedy in literature?",
    "What is comedy in literature?",
    "What is a protagonist?",
    "What is an antagonist?",
    "What is setting in a story?",
    "What is narrative point of view?",
    "What is first person narration?",
    "What is third person narration?",
    "What is omniscient narrator?",
    "What is a sonnet?",
    "What is a haiku?",
    "What is a limerick?",
    "What is free verse poetry?",
    "What is rhyme scheme?",
    "What is meter in poetry?",
    "What is stanza?",
    "What is Shakespeare known for?",
    "What is Romeo and Juliet about?",
    "What is Hamlet about?",
    "What is the theme of Macbeth?",
    "What is the theme of Othello?",
    "What is the theme of King Lear?",
    "What is A Midsummer Night's Dream about?",
    "What is the Merchant of Venice about?",
    "What is Dickens known for?",
    "What is the theme of To Kill a Mockingbird?",
    "What is Of Mice and Men about?",
    "What is the Great Gatsby about?",
    "What is Lord of the Flies about?",
    "What is Animal Farm about?",
    "What is 1984 by George Orwell about?",
    "What is Pride and Prejudice about?",
    "What is a dystopian novel?",
    "What is a utopian novel?",
    "What is a coming of age story?",
    "What is a bildungsroman?",
    "What is a gothic novel?",
    "What is romantic literature?",
    "What is modernist literature?",
    "What is post-modernist literature?",
    "What is stream of consciousness writing?",
    "What is a picaresque novel?",
    "What is an epic poem?",
    "What is an ode?",
    "What is an elegy?",
    "What is a ballad?",
    "What is blank verse?",
    "What is iambic pentameter?",
    "What is a couplet?",
    "What is a quatrain?",
    "What is a refrain in poetry?",
    "What is an anthology?",
    "What is literary criticism?",
    "What is a review?",
    "What is an analysis of a text?",
    "What is close reading?",
    "What is textual evidence?",
    "What is intertextuality?",
    "What is a genre convention?",
    "What is narrative structure?",
    "What is the three-act structure?",
    "What is a subplot?",
    "What is character development?",
    "What is static character?",
    "What is dynamic character?",

    # --- Word Forms & Misc (60) ---
    "Plural of child",
    "Past participle of go",
    "Phrasal verb examples",
    "Few vs A few",
    "Little vs A little",
    "Past tense of eat",
    "Plural of mouse",
    "Past tense of run",
    "Irregular verb examples",
    "What is possessive noun?",
    "What is a pronoun?",
    "Types of pronouns",
    "Personal pronouns",
    "Reflexive pronouns",
    "When to use a vs an?",
    "When to use the?",
    "How to improve English speaking?",
    "How to write clearly?",
    "What is reading comprehension?",
    "What is inference in reading?",
    "What is the main idea of a passage?",
    "What is context clue?",
    "What is denotation vs connotation?",
    "What is literal vs figurative language?",
    "What is fact vs opinion?",
    "What is an author's purpose?",
    "What is bias in writing?",
    "How do you analyze a poem?",
    "How do you analyze a character?",
    "What is compare and contrast essay?",
    "What is cause and effect in writing?",
    "What is the past simple of write?",
    "What is the plural of ox?",
    "What is the plural of criterion?",
    "What is the plural of datum?",
    "What is the plural of phenomenon?",
    "Past tense of bring",
    "Past tense of teach",
    "Past tense of catch",
    "Past tense of think",
    "Past tense of buy",
    "What is a phrasal verb example with get?",
    "What is a phrasal verb example with put?",
    "What is a phrasal verb example with take?",
    "What is a phrasal verb example with look?",
    "What is a phrasal verb example with come?",
    "What is a phrasal verb example with turn?",
    "What is a phrasal verb example with give?",
    "What is a compound adjective?",
    "What is hyphenation rule?",
    "What is capitalization rule?",
    "What is sentence case?",
    "What is title case?",
    "What is allcaps?",
    "What is a rhetorical question?",
    "What is an exclamatory sentence?",
    "What is an interrogative sentence?",
    "What is an imperative sentence?",
    "What is a declarative sentence?",
    "What is reported question?",
    "What is embedded question?",
]

# ==============================================================================
# BUILD DATASET
# ==============================================================================
questions = physics + math + chemistry + cs + english

subjects = (
    ['Physics'] * len(physics) +
    ['Math'] * len(math) +
    ['Chemistry'] * len(chemistry) +
    ['Computer Science'] * len(cs) +
    ['English'] * len(english)
)

print(f"Physics        : {len(physics)} questions")
print(f"Math           : {len(math)} questions")
print(f"Chemistry      : {len(chemistry)} questions")
print(f"Computer Sci   : {len(cs)} questions")
print(f"English        : {len(english)} questions")
print(f"Total          : {len(questions)} questions\n")

assert len(questions) == len(subjects), f"Mismatch! {len(questions)} vs {len(subjects)}"

df = pd.DataFrame({'question': questions, 'subject': subjects})
print(f"Training on {len(df)} questions...")

# ==============================================================================
# MODEL
# ==============================================================================
vectorizer = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1, 3),
    max_features=20000,
    min_df=1,
    sublinear_tf=True,
)

X_vec = vectorizer.fit_transform(df['question'])

model = SVC(
    kernel='linear',
    probability=True,
    C=2.0,
    class_weight='balanced',
)

model.fit(X_vec, df['subject'])
print("Model trained successfully!\n")

# ==============================================================================
# TEST
# ==============================================================================
def test(question):
    vec = vectorizer.transform([question])
    pred = model.predict(vec)[0]
    conf = model.predict_proba(vec).max()
    status = "✅" if conf > 0.6 else "⚠️"
    print(f"  {status} [{pred:>16}] ({conf:.1%})  →  {question}")

print("Testing key questions:")
test("How did Newton discover gravity?")
test("What is the difference between peers and seeds?")
test("How did Kepler discover planetary motion?")
test("Why do objects fall to the ground?")
test("Solve for x in 2x + 5 = 15")
test("Explain ionic and covalent bonding")
test("Write a Python program to print hello world")
test("Difference between there and their")
test("What is photosynthesis?")
test("What is the story of Newton and the apple?")
test("What is the difference between peers and seeds in torrenting?")
test("What is a bubble sort?")
test("Explain the water cycle")
test("What is a sonnet?")
test("What is the quadratic formula?")

# ==============================================================================
# SAVE
# ==============================================================================
joblib.dump(model, 'ai_tutor_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')
