import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
import joblib

print("Training Improved AI Tutor Model...\n")

# All questions (491 total)
questions = [
    # PHYSICS - 103 questions
    "What is the formula for acceleration due to gravity?",
    "Explain Newton's three laws of motion",
    "How does gravity work on Earth?",
    "What is kinetic energy? Give formula",
    "What is potential energy?",
    "What is Newton's second law of motion?",
    "How do you calculate force using F=ma?",
    "What is the speed of light in vacuum?",
    "Explain projectile motion",
    "What is Ohm's law?",
    "What is the unit of force in SI system?",
    "Explain the concept of work and energy",
    "State the law of conservation of energy",
    "What is friction? Types of friction",
    "Explain simple harmonic motion",
    "Difference between speed and velocity",
    "What is acceleration? Unit of acceleration",
    "Explain Archimedes' principle",
    "What is Pascal's law?",
    "What is the formula for pressure?",
    "Explain reflection and refraction of light",
    "What is the lens formula?",
    "What is electromagnetic induction?",
    "Explain Faraday's law of induction",
    "Difference between scalar and vector quantities",
    "What is momentum? Formula",
    "Law of conservation of momentum",
    "What is torque?",
    "What is angular velocity?",
    "Explain Doppler effect",
    "What is the unit of power?",
    "What is specific heat capacity?",
    "Explain latent heat of fusion and vaporization",
    "What is thermodynamics?",
    "Zeroth law of thermodynamics",
    "What is entropy?",
    "Explain wave motion and types of waves",
    "Formula for wavelength, frequency and speed",
    "What is resonance?",
    "Explain standing waves",
    "Principle of buoyancy",
    "What is viscosity?",
    "Explain surface tension",
    "SI unit of electric current",
    "Coulomb's law",
    "What is electric field?",
    "What is magnetic field?",
    "Right hand thumb rule",
    "Explain nuclear fission and nuclear fusion",
    "What is radioactivity?",
    "What is half-life of a radioactive substance?",
    "Explain photoelectric effect",
    "What is Planck's constant?",
    "Basics of quantum mechanics",
    "Theory of relativity by Einstein",
    "What is escape velocity?",
    "What is terminal velocity?",
    "Explain fluid dynamics",
    "Bernoulli's principle",
    "What is centripetal force?",
    "What is centrifugal force?",
    "Explain uniform circular motion",
    "What is gravitational potential energy?",
    "Kepler's laws of planetary motion",
    "What is Hooke's law?",
    "Explain Young's modulus",
    "What is sound wave? Speed of sound",
    "What is echo?",
    "Explain SONAR",
    "What is lens maker's formula?",
    "Difference between concave and convex lens",
    "What is mirror formula?",
    "Explain total internal reflection",
    "What is critical angle?",
    "What is optical fibre?",
    "Explain LASER",
    "What is LED?",
    "What is transistor?",
    "Explain semiconductor",
    "What is diode?",
    "Difference between AC and DC current",
    "What is transformer?",
    "Explain electromagnetic spectrum",
    "What is infrared radiation?",
    "What is ultraviolet radiation?",
    "What is gamma rays?",
    "Explain X-rays",
    "What is radioactivity decay?",
    "What is alpha, beta and gamma decay?",
    "What is binding energy?",
    "Explain mass defect",
    "What is nuclear reactor?",
    "What is solar cell?",
    "Explain wind energy",
    "What is hydropower?",
    "What is geothermal energy?",
    "Explain biomass energy",
    "What is renewable vs non-renewable energy?",
    "What is greenhouse effect?",
    "What is climate change?",
    "Explain global warming",
    "What is ozone layer depletion?",
    "What is acid rain?",

    # MATH - 103 questions
    "Solve for x in 2x + 5 = 15",
    "Solve the quadratic equation x² - 5x + 6 = 0",
    "How do I calculate the area of a circle?",
    "What is the Pythagorean theorem?",
    "Solve 3x - 7 = 20",
    "Find the roots of x² + 4x + 4 = 0",
    "What is the circumference of a circle?",
    "What is 25% of 400?",
    "Solve the system: x + y = 10, 2x - y = 4",
    "Calculate the derivative of 3x² + 2x - 5",
    "What is the integral of x²?",
    "Solve 5x + 3 = 2x + 15",
    "Area of a triangle formula",
    "Volume of a sphere formula",
    "Simplify (x² + 5x + 6)/(x+2)",
    "Difference between permutation and combination",
    "Solve x² - 9 = 0",
    "Slope of line y = 3x + 7",
    "Mean of 10, 20, 30, 40",
    "Probability of heads in coin toss",
    "Simple interest formula",
    "Compound interest formula",
    "Solve inequality 2x + 5 > 17",
    "What is a matrix?",
    "Determinant of 2x2 matrix",
    "Trigonometry basics",
    "Value of sin 90°, cos 90°",
    "Value of π",
    "Convert 45° to radians",
    "Factorial of 5",
    "What is logarithm?",
    "Solve log x = 2",
    "Distance formula",
    "Midpoint formula",
    "Arithmetic progression",
    "Geometric progression",
    "Sum of first n natural numbers",
    "Binomial theorem",
    "What is a function?",
    "Domain and range of a function",
    "Area of rectangle",
    "Volume of cylinder",
    "Surface area of cube",
    "What is prime number?",
    "LCM and HCF",
    "HCF of 12 and 18",
    "Set theory basics",
    "Venn diagram",
    "What is statistics?",
    "Standard deviation",
    "Median, mode, mean",
    "Types of angles",
    "Right angle, obtuse angle, acute angle",
    "Complementary and supplementary angles",
    "What is algebra?",
    "What is geometry?",
    "What is calculus?",
    "What is differential equation?",
    "What is limit in calculus?",
    "What is continuity?",
    "What is derivative?",
    "What is integration?",
    "What is definite integral?",
    "What is indefinite integral?",
    "Solve quadratic using formula",
    "What is discriminant?",
    "What is complex number?",
    "What is modulus?",
    "What is argument of complex number?",
    "What is vector?",
    "What is scalar triple product?",
    "What is coordinate geometry?",
    "Equation of straight line",
    "What is parabola?",
    "What is ellipse?",
    "What is hyperbola?",
    "What is circle equation?",
    "What is probability distribution?",
    "What is binomial distribution?",
    "What is normal distribution?",
    "What is hypothesis testing?",
    "What is correlation?",
    "What is regression?",
    "What is linear regression?",
    "What is exponential function?",
    "What is logarithmic function?",
    "What is trigonometric identity?",
    "What is sin²θ + cos²θ = ?",
    "What is tan θ?",
    "What is cot θ?",
    "What is sec θ?",
    "What is cosec θ?",
    "What is inverse trigonometry?",
    "What is matrix multiplication?",
    "What is transpose of matrix?",
    "What is inverse of matrix?",
    "What is eigenvalue?",
    "What is eigenvector?",
    "What is linear algebra?",
    "What is number system?",
    "What is rational number?",
    "What is irrational number?",

    # CHEMISTRY - 103 questions
    "Explain ionic and covalent bonding",
    "What happens when acid reacts with base?",
    "What is photosynthesis? Write equation",
    "What is the pH scale?",
    "Explain the periodic table",
    "Balance H2 + O2 → H2O",
    "What is Avogadro's number?",
    "What is electrolysis?",
    "Types of chemical reactions",
    "What are hydrocarbons?",
    "Atomic number of carbon",
    "Difference between atom and molecule",
    "What is valency?",
    "What are isotopes?",
    "Modern periodic law",
    "What is molar mass?",
    "Empirical and molecular formula",
    "Boyle's law",
    "Charles' law",
    "Ideal gas equation",
    "Oxidation and reduction",
    "Redox reaction examples",
    "What is a catalyst?",
    "Le Chatelier's principle",
    "Chemical equilibrium",
    "What is acid rain?",
    "What is global warming?",
    "Ozone layer depletion",
    "What is polymer?",
    "What is Bakelite?",
    "Fractional distillation of petroleum",
    "Soap and detergent",
    "Esterification reaction",
    "Saponification",
    "What is metallurgy?",
    "Rusting of iron",
    "Galvanization",
    "What is an alloy?",
    "Brass composition",
    "Chemical formula of water",
    "What is heavy water?",
    "pH of pure water",
    "Buffer solution",
    "Titration",
    "Normality, molarity, molality",
    "Law of conservation of mass",
    "Dalton's atomic theory",
    "Rutherford's atomic model",
    "Bohr's atomic model",
    "Quantum numbers",
    "Electronic configuration",
    "Aufbau principle",
    "Pauli exclusion principle",
    "Hund's rule",
    "Hybridization",
    "Sigma and pi bonds",
    "What is hydrogen bond?",
    "What is van der Waals force?",
    "What is dipole moment?",
    "What is resonance in chemistry?",
    "What is aromatic compound?",
    "What is benzene?",
    "What is functional group?",
    "What is alcohol?",
    "What is carboxylic acid?",
    "What is amine?",
    "What is ketone?",
    "What is aldehyde?",
    "What is ester?",
    "What is phenol?",
    "What is organic chemistry?",
    "What is inorganic chemistry?",
    "What is physical chemistry?",
    "What is biochemistry?",
    "What is stoichiometry?",
    "What is limiting reagent?",
    "What is yield in chemistry?",
    "What is exothermic reaction?",
    "What is endothermic reaction?",
    "What is activation energy?",
    "What is rate of reaction?",
    "What is order of reaction?",
    "What is molecular orbital theory?",
    "What is VSEPR theory?",
    "What is crystal field theory?",
    "What is coordination compound?",
    "What is ligand?",
    "What is chelate?",
    "What is isomerism?",
    "What is structural isomerism?",
    "What is stereoisomerism?",
    "What is enantiomer?",
    "What is chromatography?",
    "What is spectroscopy?",
    "What is UV-Vis spectroscopy?",
    "What is IR spectroscopy?",
    "What is NMR?",

    # COMPUTER SCIENCE - 103 questions
    "Write a Python program to print hello world",
    "How do I declare a variable in Python?",
    "What is a loop in programming?",
    "Difference between RAM and ROM",
    "What is an algorithm?",
    "How does if-else statement work?",
    "What is a function in programming?",
    "Explain object-oriented programming",
    "What is HTML used for?",
    "What is binary search?",
    "Compiler vs Interpreter",
    "What is an operating system?",
    "Explain CPU and its components",
    "Primary memory vs Secondary memory",
    "What is a database?",
    "What is SQL?",
    "What is primary key?",
    "What is recursion?",
    "Sorting algorithms",
    "Bubble sort explanation",
    "Merge sort",
    "Time complexity",
    "Big O notation",
    "What is data structure?",
    "Stack and Queue",
    "Linked list",
    "Binary tree",
    "Graph data structure",
    "Machine learning basics",
    "Artificial intelligence",
    "Difference between AI and ML",
    "What is a programming language?",
    "Uses of Python",
    "Uses of Java",
    "What is C++?",
    "What is debugging?",
    "What is an IDE?",
    "Git and GitHub",
    "Version control system",
    "HTTP vs HTTPS",
    "What is a web server?",
    "Frontend vs Backend",
    "What is an API?",
    "What is JSON?",
    "What is XML?",
    "Cybersecurity basics",
    "What is a firewall?",
    "What is phishing?",
    "Virus vs Worm",
    "Cloud computing",
    "What is AWS?",
    "Big data",
    "What is Hadoop?",
    "Blockchain technology",
    "Cryptocurrency",
    "TCP/IP model",
    "What is DNS?",
    "What is IP address?",
    "What is MAC address?",
    "What is subnetting?",
    "What is VPN?",
    "What is IoT?",
    "What is 5G?",
    "What is neural network?",
    "What is deep learning?",
    "What is computer vision?",
    "What is natural language processing?",
    "What is reinforcement learning?",
    "What is supervised learning?",
    "What is unsupervised learning?",
    "What is overfitting?",
    "What is underfitting?",
    "What is feature engineering?",
    "What is data preprocessing?",
    "What is pandas in Python?",
    "What is numpy?",
    "What is matplotlib?",
    "What is seaborn?",
    "What is scikit-learn?",
    "What is flask?",
    "What is django?",
    "What is react.js?",
    "What is node.js?",
    "What is REST API?",
    "What is GraphQL?",
    "What is Docker?",
    "What is Kubernetes?",
    "What is microservices?",
    "What is monolithic architecture?",
    "What is agile methodology?",
    "What is scrum?",
    "What is waterfall model?",
    "What is SDLC?",
    "What is software testing?",
    "What is unit testing?",
    "What is integration testing?",

    # ENGLISH - 79 questions
    "Why is grammar important in English?",
    "Difference between there and their",
    "Explain simile and metaphor",
    "Difference between noun and verb",
    "Correct the sentence: He go to school yesterday",
    "Active and passive voice",
    "Synonym for beautiful",
    "How to write a formal email?",
    "Past tense of eat",
    "Meaning of ubiquitous",
    "Difference between affect and effect",
    "What is a preposition?",
    "Direct and indirect speech",
    "What is a conjunction?",
    "What is an adjective?",
    "What is an adverb?",
    "Who vs Whom",
    "Correct: She is more taller than me",
    "What is a proverb?",
    "Idiom with example",
    "Alliteration",
    "Personification",
    "Hyperbole",
    "Onomatopoeia",
    "Plural of child",
    "Past participle of go",
    "Subject-verb agreement",
    "Tenses in English",
    "Present perfect tense",
    "Future continuous tense",
    "Synonym for happy",
    "Antonym for difficult",
    "What is a homophone?",
    "Its vs It's",
    "What is a paragraph?",
    "How to write a letter",
    "Narrative essay",
    "Descriptive writing",
    "Thesis statement",
    "Topic sentence",
    "Coherence in writing",
    "Formal vs informal language",
    "Punctuation marks",
    "Use of comma",
    "Question tag",
    "Reported speech",
    "Conditional sentences",
    "Zero conditional",
    "First conditional",
    "Phrasal verb",
    "Meaning of break down",
    "Lend vs Borrow",
    "Collective noun",
    "Abstract noun",
    "Countable and uncountable nouns",
    "Few vs A few",
    "Little vs A little",
    "Modal verbs",
    "Should vs Must",
    "What is a clause?",
    "What is a phrase?",
    "What is a sentence?",
    "Simple, compound and complex sentence",
    "What is a synonym?",
    "What is an antonym?",
    "What is a homonym?",
    "What is a palindrome?",
    "What is an acronym?",
    "What is an abbreviation?",
    "What is a suffix?",
    "What is a prefix?",
    "Root word",
    "What is etymology?",
    "What is literature?",
    "What is poetry?",
    "What is prose?",
    "What is drama?",
    "What is fiction vs non-fiction?",
    "What is biography?",
    "What is autobiography?",
    "What is a novel?",
    "What is a short story?",
    "What is a character sketch?",
    "What is plot?",
    "What is climax?",
    "What is theme?",
    "What is symbolism?",
    "What is irony?",
    "What is satire?",
    "What is oxymoron?",
    "What is euphemism?",
    "What is paradox?",
    "What is rhetoric?"
]

# Create subjects list matching exact number of questions
subjects = ['Physics']*103 + ['Math']*103 + ['Chemistry']*103 + ['Computer Science']*103 + ['English']*79

print(f"Number of questions: {len(questions)}")
print(f"Number of subjects : {len(subjects)}")

data = {
    'question': questions,
    'subject': subjects
}

df = pd.DataFrame(data)

print(f"\nTraining on {len(df)} questions...")

# Improved Vectorizer and Model
vectorizer = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1, 3),      # unigrams + bigrams + trigrams
    max_features=10000,
    min_df=2
)

X_vec = vectorizer.fit_transform(df['question'])

model = SVC(
    kernel='linear',
    probability=True,
    C=1.5,
    class_weight='balanced'
)

model.fit(X_vec, df['subject'])

print("Improved model trained successfully!")

# Test function
def test_ai_tutor(question):
    question_vec = vectorizer.transform([question])
    prediction = model.predict(question_vec)[0]
    confidence = model.predict_proba(question_vec).max()
    
    print(f"Question: {question}")
    print(f"Predicted Subject: {prediction}")
    print(f"Confidence: {confidence:.1%}")
    print("-" * 80)

print("\nTesting Improved Model:")
test_ai_tutor("Solve for x in 2x + 5 = 15")
test_ai_tutor("Explain Newton's three laws of motion")
test_ai_tutor("Explain ionic and covalent bonding")
test_ai_tutor("How do I declare a variable in Python?")
test_ai_tutor("What is the difference between there and their?")
test_ai_tutor("What is the area of a circle with radius 5?")
test_ai_tutor("What is photosynthesis?")
test_ai_tutor("Write a Python program to print hello world")

# Save the improved model
joblib.dump(model, 'ai_tutor_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')

print("\n✅ Improved model trained and saved successfully!")
