import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
import joblib

print("Training Expanded AI Tutor Model (1500+ questions)...\n")

# ==============================================================================
# PHYSICS - 300 questions
# ==============================================================================
physics = [
    # Newton & Gravity (natural discovery-style questions)
    "How did Newton discover gravity?",
    "What inspired Newton to think about gravity?",
    "Tell me the story of Newton and the apple",
    "How was gravity discovered?",
    "Who discovered the law of gravitation?",
    "What is Newton's law of universal gravitation?",
    "How did scientists figure out gravity exists?",
    "What is the formula for gravitational force?",
    "Why do objects fall to the ground?",
    "What makes things fall down?",
    "How does gravity pull objects?",
    "What is the gravitational constant G?",
    "How does gravity work on Earth?",
    "What is the acceleration due to gravity?",
    "What is the formula for acceleration due to gravity?",
    "Why is gravity weaker on the moon?",
    "How did Galileo study gravity?",
    "What is gravitational potential energy?",
    "How does gravity affect satellites?",
    "What is free fall?",
    # Newton's Laws
    "Explain Newton's three laws of motion",
    "What is Newton's first law?",
    "What is Newton's second law of motion?",
    "What is Newton's third law?",
    "Give an example of Newton's first law",
    "Give an example of Newton's third law in real life",
    "How do I calculate force using F equals ma?",
    "What is inertia?",
    "Why does a book stay on the table?",
    "Why does a rocket move forward?",
    "What is action and reaction?",
    "How does Newton's second law relate force and acceleration?",
    # Energy & Work
    "What is kinetic energy? Give formula",
    "What is potential energy?",
    "Explain the concept of work and energy",
    "State the law of conservation of energy",
    "What is the difference between kinetic and potential energy?",
    "How is work calculated in physics?",
    "What is mechanical energy?",
    "What is the unit of energy?",
    "What is power in physics?",
    "What is the unit of power?",
    "How is power related to work?",
    "What is energy transformation?",
    "Give examples of energy conversion",
    # Motion & Kinematics
    "What is acceleration? Unit of acceleration",
    "Difference between speed and velocity",
    "Explain projectile motion",
    "What is uniform motion?",
    "What is non-uniform motion?",
    "What are the equations of motion?",
    "What is displacement?",
    "What is distance vs displacement?",
    "How do you calculate velocity?",
    "What is average speed?",
    "What is instantaneous velocity?",
    "Explain uniform circular motion",
    "What is centripetal force?",
    "What is centrifugal force?",
    "What is angular velocity?",
    "What is torque?",
    "What is terminal velocity?",
    "What is escape velocity?",
    # Momentum
    "What is momentum? Formula",
    "Law of conservation of momentum",
    "What is impulse?",
    "How is momentum related to force?",
    "What is collision in physics?",
    "Elastic vs inelastic collision",
    # Forces & Friction
    "What is friction? Types of friction",
    "What is static friction?",
    "What is kinetic friction?",
    "How does friction affect motion?",
    "What is normal force?",
    "What is tension in physics?",
    # Waves & Sound
    "Explain wave motion and types of waves",
    "Formula for wavelength frequency and speed",
    "What is resonance?",
    "Explain standing waves",
    "What is sound wave? Speed of sound",
    "What is echo?",
    "Explain SONAR",
    "Explain Doppler effect",
    "What is ultrasound?",
    "What is infrasound?",
    "What is amplitude of a wave?",
    "What is frequency?",
    "What is wavelength?",
    "What is the relationship between frequency and pitch?",
    # Light & Optics
    "Explain reflection and refraction of light",
    "What is the lens formula?",
    "What is mirror formula?",
    "Difference between concave and convex lens",
    "Explain total internal reflection",
    "What is critical angle?",
    "What is optical fibre?",
    "What is the speed of light in vacuum?",
    "What is dispersion of light?",
    "What is rainbow?",
    "What is refractive index?",
    "What is prism?",
    "What is lens maker's formula?",
    "Explain LASER",
    # Electricity & Magnetism
    "What is Ohm's law?",
    "What is electric field?",
    "What is magnetic field?",
    "What is electromagnetic induction?",
    "Explain Faraday's law of induction",
    "Right hand thumb rule",
    "What is electric current?",
    "What is voltage?",
    "What is resistance?",
    "What is capacitor?",
    "What is inductor?",
    "Coulomb's law",
    "SI unit of electric current",
    "Difference between AC and DC current",
    "What is transformer?",
    "What is LED?",
    "What is transistor?",
    "Explain semiconductor",
    "What is diode?",
    # Thermodynamics
    "What is specific heat capacity?",
    "Explain latent heat of fusion and vaporization",
    "What is thermodynamics?",
    "Zeroth law of thermodynamics",
    "What is entropy?",
    "What is temperature?",
    "What is heat transfer?",
    "Explain conduction convection and radiation",
    "What is thermal expansion?",
    # Fluid Mechanics
    "Explain Archimedes principle",
    "What is Pascal's law?",
    "What is the formula for pressure?",
    "Principle of buoyancy",
    "What is viscosity?",
    "Explain surface tension",
    "Explain fluid dynamics",
    "Bernoulli's principle",
    "Why does a ship float?",
    "Why does ice float on water?",
    # Modern Physics
    "Explain nuclear fission and nuclear fusion",
    "What is radioactivity?",
    "What is half-life of a radioactive substance?",
    "Explain photoelectric effect",
    "What is Planck's constant?",
    "Basics of quantum mechanics",
    "Theory of relativity by Einstein",
    "What is alpha beta and gamma decay?",
    "What is binding energy?",
    "Explain mass defect",
    "What is nuclear reactor?",
    "What is X-ray?",
    "What is gamma ray?",
    "What is electromagnetic spectrum?",
    # Elasticity
    "What is Hooke's law?",
    "Explain Young's modulus",
    "What is stress and strain?",
    "What is elastic limit?",
    # Celestial
    "Kepler's laws of planetary motion",
    "How did Kepler discover planetary motion?",
    "What is the story behind Kepler's laws?",
    "How do planets orbit the sun?",
    "What keeps planets in orbit?",
    "What is orbital velocity?",
    "What is black hole?",
    "What is the Big Bang theory?",
    "How was the universe formed?",
    # Energy Sources
    "What is solar cell?",
    "Explain wind energy",
    "What is hydropower?",
    "What is geothermal energy?",
    "Explain biomass energy",
    "What is renewable vs non-renewable energy?",
    "What is greenhouse effect?",
    "What is climate change?",
    "Explain global warming",
    "What is ozone layer depletion?",
    "What is acid rain?",
    # Simple Machines
    "What is simple harmonic motion?",
    "What is a lever?",
    "What is a pulley?",
    "How does an inclined plane work?",
    # Vectors
    "Difference between scalar and vector quantities",
    "What is dot product?",
    "What is cross product?",
    "How do you add vectors?",
    "What is a unit vector?",
]

# ==============================================================================
# MATH - 300 questions
# ==============================================================================
math = [
    # Algebra
    "Solve for x in 2x + 5 = 15",
    "Solve the quadratic equation x squared minus 5x plus 6 equals 0",
    "Solve 3x - 7 = 20",
    "Find the roots of x squared plus 4x plus 4 equals 0",
    "Solve 5x + 3 = 2x + 15",
    "Solve x squared minus 9 equals 0",
    "Solve inequality 2x + 5 > 17",
    "How do I solve linear equations?",
    "How do I expand brackets in algebra?",
    "Simplify x squared plus 5x plus 6 divided by x plus 2",
    "Solve the system of equations x plus y equals 10 and 2x minus y equals 4",
    "What is algebra?",
    "What is a variable in math?",
    "What is a coefficient?",
    "What is a constant in algebra?",
    "How do I factorize a quadratic?",
    "What is completing the square?",
    "Solve quadratic using the quadratic formula",
    "What is discriminant?",
    "What does discriminant tell us about roots?",
    "What is a complex number?",
    "What is modulus of a complex number?",
    "What is the argument of a complex number?",
    # Geometry
    "How do I calculate the area of a circle?",
    "What is the Pythagorean theorem?",
    "What is the circumference of a circle?",
    "Area of a triangle formula",
    "Volume of a sphere formula",
    "Area of rectangle",
    "Volume of cylinder",
    "Surface area of cube",
    "Types of angles",
    "Right angle obtuse angle acute angle",
    "Complementary and supplementary angles",
    "What is geometry?",
    "What is a polygon?",
    "What is a quadrilateral?",
    "Properties of a parallelogram",
    "Properties of a rhombus",
    "What is a trapezoid?",
    "What is congruence in geometry?",
    "What is similarity in geometry?",
    "What is a tangent to a circle?",
    "What is a chord?",
    "What is the angle in a semicircle?",
    "What is the exterior angle of a triangle?",
    "Pythagoras theorem proof",
    "What is Heron's formula?",
    # Coordinate Geometry
    "Distance formula",
    "Midpoint formula",
    "Slope of line y equals 3x plus 7",
    "Equation of straight line",
    "What is coordinate geometry?",
    "What is parabola?",
    "What is ellipse?",
    "What is hyperbola?",
    "What is circle equation?",
    "What is the slope of a horizontal line?",
    "What is the slope of a vertical line?",
    "How do you find the equation of a line through two points?",
    # Calculus
    "Calculate the derivative of 3x squared plus 2x minus 5",
    "What is the integral of x squared?",
    "What is calculus?",
    "What is a limit in calculus?",
    "What is continuity?",
    "What is a derivative?",
    "What is integration?",
    "What is definite integral?",
    "What is indefinite integral?",
    "What is differential equation?",
    "How do you differentiate sin x?",
    "How do you differentiate cos x?",
    "How do you differentiate e to the x?",
    "What is the chain rule?",
    "What is the product rule?",
    "What is the quotient rule?",
    "What is integration by parts?",
    "What is substitution in integration?",
    "What is the fundamental theorem of calculus?",
    "What is maxima and minima?",
    "How do you find turning points?",
    # Trigonometry
    "Trigonometry basics",
    "Value of sin 90 degrees cos 90 degrees",
    "Convert 45 degrees to radians",
    "What is trigonometric identity?",
    "What is sin squared theta plus cos squared theta?",
    "What is tan theta?",
    "What is cot theta?",
    "What is sec theta?",
    "What is cosec theta?",
    "What is inverse trigonometry?",
    "What is sine rule?",
    "What is cosine rule?",
    "How do you solve trigonometric equations?",
    "What is the unit circle?",
    "What are the trigonometric ratios?",
    "How do I find angles using trigonometry?",
    # Statistics & Probability
    "Mean of 10 20 30 40",
    "Probability of heads in coin toss",
    "What is statistics?",
    "Standard deviation",
    "Median mode mean",
    "What is probability distribution?",
    "What is binomial distribution?",
    "What is normal distribution?",
    "What is hypothesis testing?",
    "What is correlation?",
    "What is regression?",
    "What is linear regression?",
    "What is variance?",
    "What is range in statistics?",
    "What is cumulative frequency?",
    "How do you draw a histogram?",
    "What is a bar chart?",
    "What is a pie chart?",
    "What is sample and population in statistics?",
    # Number Theory
    "What is a prime number?",
    "LCM and HCF",
    "HCF of 12 and 18",
    "What is a rational number?",
    "What is an irrational number?",
    "What is number system?",
    "What is factorial of 5?",
    "What is value of pi?",
    "What is Euclid's division algorithm?",
    "What is divisibility rule?",
    "What are factors of a number?",
    "What are multiples of a number?",
    "What is a composite number?",
    "What is a co-prime number?",
    # Sequences & Series
    "Arithmetic progression",
    "Geometric progression",
    "Sum of first n natural numbers",
    "Binomial theorem",
    "What is sum of arithmetic series?",
    "What is sum of geometric series?",
    "What is infinite geometric series?",
    "What is nth term of AP?",
    "What is nth term of GP?",
    "What is Fibonacci sequence?",
    # Functions
    "What is a function?",
    "Domain and range of a function",
    "What is an exponential function?",
    "What is a logarithmic function?",
    "What is a composite function?",
    "What is an inverse function?",
    "What is even and odd function?",
    "What is a periodic function?",
    "What is a bijective function?",
    "What is a surjective function?",
    # Logarithms
    "What is logarithm?",
    "Solve log x equals 2",
    "What is natural log?",
    "Laws of logarithms",
    "Change of base formula",
    "What is log base 10?",
    # Matrices & Vectors
    "What is a matrix?",
    "Determinant of 2x2 matrix",
    "What is matrix multiplication?",
    "What is transpose of matrix?",
    "What is inverse of matrix?",
    "What is eigenvalue?",
    "What is eigenvector?",
    "What is linear algebra?",
    "What is a vector in math?",
    "What is scalar triple product?",
    # Percentages & Finance
    "What is 25 percent of 400?",
    "Simple interest formula",
    "Compound interest formula",
    "How do you calculate percentage?",
    "What is percentage increase?",
    "What is profit and loss?",
    # Permutations & Sets
    "Difference between permutation and combination",
    "What is set theory?",
    "Venn diagram",
    "What is union and intersection of sets?",
    "How many ways can you arrange 5 objects?",
]

# ==============================================================================
# CHEMISTRY - 300 questions
# ==============================================================================
chemistry = [
    # Bonding
    "Explain ionic and covalent bonding",
    "What is a covalent bond?",
    "What is an ionic bond?",
    "What is a metallic bond?",
    "What is hydrogen bonding?",
    "What is a polar covalent bond?",
    "What is electronegativity?",
    "What is valency?",
    "What is Lewis structure?",
    "What is VSEPR theory?",
    "What is hybridization in chemistry?",
    # Acids, Bases & pH
    "What happens when acid reacts with base?",
    "What is the pH scale?",
    "What is an acid?",
    "What is a base?",
    "What is a neutral solution?",
    "What is neutralization reaction?",
    "Strong acid vs weak acid",
    "What is Arrhenius acid?",
    "What is Bronsted Lowry acid?",
    "What is pH of blood?",
    "What is litmus paper?",
    # Photosynthesis & Biology Chemistry
    "What is photosynthesis? Write equation",
    "What is the chemical equation for photosynthesis?",
    "What gas is released during photosynthesis?",
    "What is chlorophyll?",
    "What is cellular respiration?",
    "What is the equation for respiration?",
    # Periodic Table
    "Explain the periodic table",
    "Modern periodic law",
    "What is atomic number of carbon?",
    "What is an element?",
    "What is a period in the periodic table?",
    "What is a group in the periodic table?",
    "What are noble gases?",
    "What are halogens?",
    "What are alkali metals?",
    "What are alkaline earth metals?",
    "What are transition metals?",
    "What is the most abundant element on earth?",
    "What is atomic mass?",
    "What is atomic number?",
    # Atoms & Molecules
    "Difference between atom and molecule",
    "What are isotopes?",
    "What is atomic structure?",
    "What is Bohr model of atom?",
    "What is electron configuration?",
    "What are subatomic particles?",
    "What is proton neutron electron?",
    "What is nucleus of an atom?",
    "What is orbital in chemistry?",
    "What is quantum number?",
    # Chemical Reactions
    "Types of chemical reactions",
    "Balance H2 plus O2 gives H2O",
    "What is a chemical equation?",
    "What is balancing a chemical equation?",
    "What is combination reaction?",
    "What is decomposition reaction?",
    "What is displacement reaction?",
    "What is double displacement reaction?",
    "What is precipitation reaction?",
    "What is combustion reaction?",
    "What is exothermic reaction?",
    "What is endothermic reaction?",
    # Stoichiometry & Moles
    "What is Avogadro's number?",
    "What is molar mass?",
    "Empirical and molecular formula",
    "What is a mole?",
    "What is stoichiometry?",
    "How do you calculate moles?",
    "What is molarity?",
    "What is molality?",
    # Gases
    "Boyle's law",
    "Charles law",
    "Ideal gas equation",
    "What is Avogadro's law?",
    "What is Gay-Lussac's law?",
    "What is Dalton's law of partial pressure?",
    "What is kinetic molecular theory?",
    "What is diffusion?",
    "What is effusion?",
    # Redox & Electrochemistry
    "Oxidation and reduction",
    "Redox reaction examples",
    "What is electrolysis?",
    "What is electrochemical cell?",
    "What is galvanic cell?",
    "What is oxidation state?",
    "What is oxidizing agent?",
    "What is reducing agent?",
    "What is electrolyte?",
    "What is electrode?",
    "What is anode and cathode?",
    # Equilibrium & Kinetics
    "What is a catalyst?",
    "Le Chatelier's principle",
    "Chemical equilibrium",
    "What is rate of reaction?",
    "What affects rate of reaction?",
    "What is activation energy?",
    "What is reaction rate constant?",
    "What is order of reaction?",
    "What is equilibrium constant?",
    "What is Kp and Kc?",
    # Organic Chemistry
    "What are hydrocarbons?",
    "What is Bakelite?",
    "Fractional distillation of petroleum",
    "Soap and detergent",
    "Esterification reaction",
    "Saponification",
    "What is polymer?",
    "What is organic chemistry?",
    "What is functional group?",
    "What is isomer?",
    "What is alkane alkene alkyne?",
    "What is benzene?",
    "What is alcohol in chemistry?",
    "What is carboxylic acid?",
    "What is aldehyde?",
    "What is ketone?",
    "What is ester?",
    "What is addition reaction?",
    "What is substitution reaction?",
    "What is polymerization?",
    "What is nylon?",
    "What is PVC?",
    # Metals & Materials
    "What is metallurgy?",
    "Rusting of iron",
    "Galvanization",
    "What is an alloy?",
    "What is corrosion?",
    "How to prevent rusting?",
    "What is steel?",
    "What is brass?",
    "What is bronze?",
    "What is stainless steel?",
    "What is thermite reaction?",
    "Extraction of aluminium",
    "Extraction of iron",
    "What is smelting?",
    # Solutions
    "What is a solution?",
    "What is solubility?",
    "What is saturated solution?",
    "What is concentration?",
    "What is boiling point elevation?",
    "What is freezing point depression?",
    "What is osmotic pressure?",
    "What is osmosis?",
    "What is a colloid?",
    "What is suspension?",
    # Environmental
    "What is water pollution?",
    "What is air pollution?",
    "What is soil pollution?",
    "What causes acid rain?",
    "What is ozone depletion?",
    "What is greenhouse gas?",
    "What is carbon dioxide in atmosphere?",
    "What is CFC?",
    # Nuclear & Thermo
    "What is radioactive decay?",
    "What is nuclear chemistry?",
    "What is carbon dating?",
    "What is enthalpy?",
    "What is Hess's law?",
    "What is heat of combustion?",
    "What is heat of formation?",
    # Lab techniques
    "What is chromatography?",
    "What is distillation?",
    "What is filtration?",
    "What is crystallization?",
    "What is titration?",
    "What is indicator in chemistry?",
    "What is universal indicator?",
    "What is flame test?",
    "What is qualitative analysis?",
]

# ==============================================================================
# COMPUTER SCIENCE - 300 questions
# ==============================================================================
cs = [
    # Programming Basics
    "Write a Python program to print hello world",
    "How do I declare a variable in Python?",
    "What is a loop in programming?",
    "How does if-else statement work?",
    "What is a function in programming?",
    "What is a programming language?",
    "What is debugging?",
    "What is an IDE?",
    "What is pseudocode?",
    "What is flowchart?",
    "What is syntax error?",
    "What is runtime error?",
    "What is logic error?",
    "What is a comment in code?",
    "What is indentation in Python?",
    "What is a for loop?",
    "What is a while loop?",
    "What is break and continue?",
    "What is a nested loop?",
    "What is an array?",
    "What is a list in Python?",
    "What is a tuple in Python?",
    "What is a dictionary in Python?",
    "What is a set in Python?",
    "What is string in programming?",
    "How do you concatenate strings?",
    "What is string slicing?",
    "What is type casting?",
    "What is input and output in programming?",
    # OOP
    "Explain object oriented programming",
    "What is a class?",
    "What is an object?",
    "What is inheritance?",
    "What is polymorphism?",
    "What is encapsulation?",
    "What is abstraction?",
    "What is constructor?",
    "What is method in OOP?",
    "What is instance variable?",
    "What is class variable?",
    "What is method overriding?",
    "What is method overloading?",
    "What is interface?",
    "What is abstract class?",
    # Data Structures & Algorithms
    "What is an algorithm?",
    "What is data structure?",
    "Stack and Queue",
    "Linked list",
    "Binary tree",
    "Graph data structure",
    "Sorting algorithms",
    "Bubble sort explanation",
    "Merge sort",
    "Time complexity",
    "Big O notation",
    "What is binary search?",
    "What is linear search?",
    "What is recursion?",
    "What is dynamic programming?",
    "What is greedy algorithm?",
    "What is hash table?",
    "What is a heap?",
    "What is a priority queue?",
    "What is depth first search?",
    "What is breadth first search?",
    "What is quick sort?",
    "What is insertion sort?",
    "What is selection sort?",
    "Space complexity",
    "Best case average case worst case",
    # Hardware
    "Difference between RAM and ROM",
    "What is CPU?",
    "Explain CPU and its components",
    "Primary memory vs secondary memory",
    "What is hard drive?",
    "What is SSD?",
    "What is motherboard?",
    "What is GPU?",
    "What is cache memory?",
    "What is register?",
    "What is ALU?",
    "What is control unit?",
    "What is fetch decode execute cycle?",
    "What is clock speed?",
    "What is bit and byte?",
    # OS & Systems
    "What is an operating system?",
    "What is process in OS?",
    "What is thread?",
    "What is multithreading?",
    "What is deadlock?",
    "What is virtual memory?",
    "What is paging?",
    "What is file system?",
    "What is shell?",
    "What is kernel?",
    "What is Linux?",
    "What is process scheduling?",
    "What is context switching?",
    # Databases
    "What is a database?",
    "What is SQL?",
    "What is primary key?",
    "What is foreign key?",
    "What is normalization?",
    "What is a relational database?",
    "What is NoSQL?",
    "What is JOIN in SQL?",
    "What is SELECT statement?",
    "What is WHERE clause?",
    "What is INDEX in database?",
    "What is ACID in database?",
    "What is MongoDB?",
    "What is transaction in database?",
    # Networking
    "TCP IP model",
    "What is DNS?",
    "What is IP address?",
    "What is MAC address?",
    "What is subnetting?",
    "What is VPN?",
    "What is firewall?",
    "HTTP vs HTTPS",
    "What is a web server?",
    "What is bandwidth?",
    "What is latency?",
    "What is OSI model?",
    "What is router?",
    "What is protocol?",
    # Web & Software Dev
    "Frontend vs backend",
    "What is HTML used for?",
    "What is CSS?",
    "What is JavaScript?",
    "What is an API?",
    "What is JSON?",
    "What is XML?",
    "What is REST API?",
    "What is GraphQL?",
    "What is flask?",
    "What is django?",
    "What is react.js?",
    "What is node.js?",
    "What is Docker?",
    "What is Kubernetes?",
    "What is microservices?",
    "What is monolithic architecture?",
    "Git and GitHub",
    "Version control system",
    "What is agile methodology?",
    "What is scrum?",
    "What is SDLC?",
    "What is software testing?",
    "What is unit testing?",
    # AI & ML
    "Machine learning basics",
    "Artificial intelligence basics",
    "Difference between AI and ML",
    "What is neural network?",
    "What is deep learning?",
    "What is computer vision?",
    "What is natural language processing?",
    "What is reinforcement learning?",
    "What is supervised learning?",
    "What is unsupervised learning?",
    "What is overfitting?",
    "What is underfitting?",
    "What is feature engineering?",
    "What is data preprocessing?",
    "What is pandas in Python?",
    "What is numpy?",
    "What is matplotlib?",
    "What is scikit-learn?",
    # Cybersecurity
    "Cybersecurity basics",
    "What is phishing?",
    "Virus vs Worm",
    "What is malware?",
    "What is ransomware?",
    "What is encryption?",
    "What is hashing?",
    "What is SSL certificate?",
    "What is two factor authentication?",
    "What is SQL injection?",
    # Emerging Tech
    "Cloud computing",
    "What is AWS?",
    "Big data",
    "What is Hadoop?",
    "Blockchain technology",
    "Cryptocurrency",
    "What is IoT?",
    "What is 5G?",
    "What is edge computing?",
    "What is quantum computing?",
    "What is augmented reality?",
    "What is virtual reality?",
    # Languages
    "Uses of Python",
    "Uses of Java",
    "What is C++?",
    "What is C programming?",
    "Difference between Python and Java",
    "What is TypeScript?",
    "What is Kotlin?",
]

# ==============================================================================
# ENGLISH - 300 questions
# ==============================================================================
english = [
    # Grammar
    "Why is grammar important in English?",
    "Difference between there and their",
    "Difference between noun and verb",
    "Correct the sentence He go to school yesterday",
    "Active and passive voice",
    "What is a preposition?",
    "Direct and indirect speech",
    "What is a conjunction?",
    "What is an adjective?",
    "What is an adverb?",
    "Who vs Whom",
    "Correct She is more taller than me",
    "Subject verb agreement",
    "Tenses in English",
    "Present perfect tense",
    "Future continuous tense",
    "Punctuation marks",
    "Use of comma",
    "Question tag",
    "Reported speech",
    "Conditional sentences",
    "Zero conditional",
    "First conditional",
    "Modal verbs",
    "Should vs Must",
    "What is a clause?",
    "What is a phrase?",
    "What is a sentence?",
    "Simple compound and complex sentence",
    "What is a subordinate clause?",
    "What is a relative clause?",
    "What is a noun clause?",
    "What is an adverbial clause?",
    "What is subject in a sentence?",
    "What is predicate?",
    "What is object in grammar?",
    "What is a gerund?",
    "What is an infinitive?",
    "What is a participle?",
    "What is a dangling modifier?",
    "What is the Oxford comma?",
    "How to use semicolon?",
    "How to use colon?",
    "When to use apostrophe?",
    "Its vs It's",
    "Your vs You're",
    "They're vs Their vs There",
    "Then vs Than",
    "Affect vs Effect",
    "Fewer vs Less",
    "Lie vs Lay",
    # Vocabulary
    "Synonym for beautiful",
    "Antonym for difficult",
    "Meaning of ubiquitous",
    "What is a homophone?",
    "What is a synonym?",
    "What is an antonym?",
    "What is a homonym?",
    "What is a palindrome?",
    "What is an acronym?",
    "What is an abbreviation?",
    "What is a suffix?",
    "What is a prefix?",
    "Root word examples",
    "What is etymology?",
    "What is a portmanteau word?",
    "Synonym for happy",
    "Synonym for sad",
    "Synonym for big",
    "Antonym for brave",
    "What is vocabulary?",
    "How to improve vocabulary?",
    "What is a compound word?",
    "What is an idiom?",
    "Meaning of break down",
    "Lend vs Borrow",
    "Meaning of bite the bullet",
    "Meaning of kick the bucket",
    "Meaning of spill the beans",
    "Meaning of hit the nail on the head",
    # Figures of Speech
    "Explain simile and metaphor",
    "What is a proverb?",
    "Idiom with example",
    "Alliteration",
    "Personification",
    "Hyperbole",
    "Onomatopoeia",
    "What is symbolism?",
    "What is irony?",
    "What is satire?",
    "What is oxymoron?",
    "What is euphemism?",
    "What is paradox?",
    "What is rhetoric?",
    "What is foreshadowing?",
    "What is flashback in literature?",
    "What is allegory?",
    "What is allusion?",
    "What is anaphora?",
    "What is assonance?",
    "What is consonance?",
    "What is juxtaposition?",
    "What is sarcasm?",
    "What is understatement?",
    "What is imagery in literature?",
    "What is tone in writing?",
    "What is mood in literature?",
    "What is voice in writing?",
    # Writing Skills
    "How to write a formal email?",
    "How to write a letter",
    "Narrative essay",
    "Descriptive writing",
    "Thesis statement",
    "Topic sentence",
    "Coherence in writing",
    "Formal vs informal language",
    "How to write an essay introduction?",
    "How to write a conclusion?",
    "What is a paragraph?",
    "What is a body paragraph?",
    "How do you write a persuasive essay?",
    "How do you write an argumentative essay?",
    "What is expository writing?",
    "What is a cover letter?",
    "How to write a resume?",
    "What is a summary?",
    "How do you paraphrase?",
    "What is citation?",
    "What is plagiarism?",
    "What is proofreading?",
    "What is editing?",
    "What is drafting?",
    # Literature
    "What is literature?",
    "What is poetry?",
    "What is prose?",
    "What is drama?",
    "What is fiction vs non-fiction?",
    "What is biography?",
    "What is autobiography?",
    "What is a novel?",
    "What is a short story?",
    "What is a character sketch?",
    "What is plot?",
    "What is climax?",
    "What is theme?",
    "What is genre in literature?",
    "What is tragedy in literature?",
    "What is comedy in literature?",
    "What is a protagonist?",
    "What is an antagonist?",
    "What is setting in a story?",
    "What is narrative point of view?",
    "What is first person narration?",
    "What is third person narration?",
    "What is omniscient narrator?",
    "What is a sonnet?",
    "What is a haiku?",
    "What is a limerick?",
    "What is free verse poetry?",
    "What is rhyme scheme?",
    "What is meter in poetry?",
    "What is stanza?",
    "What is Shakespeare known for?",
    "What is Romeo and Juliet about?",
    "What is Hamlet about?",
    "What is the theme of Macbeth?",
    # Word Forms & Usage
    "Plural of child",
    "Past participle of go",
    "Phrasal verb examples",
    "Collective noun",
    "Abstract noun",
    "Countable and uncountable nouns",
    "Few vs A few",
    "Little vs A little",
    "Past tense of eat",
    "Plural of mouse",
    "Past tense of run",
    "Irregular verb examples",
    "What is possessive noun?",
    "What is proper noun?",
    "What is common noun?",
    "What is a pronoun?",
    "Types of pronouns",
    "Personal pronouns",
    "Reflexive pronouns",
    "What is a determiner?",
    "What is an article in grammar?",
    "When to use a vs an?",
    "When to use the?",
    # Reading & Communication
    "How to improve English speaking?",
    "How to write clearly?",
    "What is reading comprehension?",
    "What is inference in reading?",
    "What is the main idea of a passage?",
    "What is context clue?",
    "What is denotation vs connotation?",
    "What is literal vs figurative language?",
    "What is fact vs opinion?",
    "What is an author's purpose?",
    "What is bias in writing?",
    "How do you analyze a poem?",
    "How do you analyze a character?",
    "What is compare and contrast essay?",
    "What is cause and effect in writing?",
]

# ==============================================================================
# BUILD DATASET
# ==============================================================================
questions = physics + math + chemistry + cs + english

subjects = (
    ['Physics'] * len(physics) +
    ['Math'] * len(math) +
    ['Chemistry'] * len(chemistry) +
    ['Computer Science'] * len(cs) +
    ['English'] * len(english)
)

print(f"Physics        : {len(physics)} questions")
print(f"Math           : {len(math)} questions")
print(f"Chemistry      : {len(chemistry)} questions")
print(f"Computer Sci   : {len(cs)} questions")
print(f"English        : {len(english)} questions")
print(f"Total          : {len(questions)} questions\n")

assert len(questions) == len(subjects), "Mismatch between questions and subjects!"

df = pd.DataFrame({'question': questions, 'subject': subjects})
print(f"Training on {len(df)} questions...")

# ==============================================================================
# MODEL
# ==============================================================================
vectorizer = TfidfVectorizer(
    stop_words='english',
    ngram_range=(1, 3),
    max_features=15000,
    min_df=1,
    sublinear_tf=True,
)

X_vec = vectorizer.fit_transform(df['question'])

model = SVC(
    kernel='linear',
    probability=True,
    C=2.0,
    class_weight='balanced',
)

model.fit(X_vec, df['subject'])
print("Model trained successfully!\n")

# ==============================================================================
# TEST
# ==============================================================================
def test(question):
    vec = vectorizer.transform([question])
    pred = model.predict(vec)[0]
    conf = model.predict_proba(vec).max()
    print(f"  Q: {question}")
    print(f"  → {pred} ({conf:.1%})\n")

print("Testing key questions:")
test("How did Newton discover gravity?")
test("What is the difference between peers and seeds?")
test("How did Kepler discover planetary motion?")
test("Why do objects fall to the ground?")
test("Solve for x in 2x + 5 = 15")
test("Explain ionic and covalent bonding")
test("Write a Python program to print hello world")
test("Difference between there and their")
test("What is photosynthesis?")
test("What is the story of the apple and Newton?")

# ==============================================================================
# SAVE
# ==============================================================================
joblib.dump(model, 'ai_tutor_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')
print("✅ Model saved: ai_tutor_model.pkl + vectorizer.pkl")
print("Upload both .pkl files to your GitHub repo to deploy!")
